Sous Slice id acte specifique / acte hors cabinet
ansforge/IG-fhir-repertoire-offre-ressources-sante pull request #132
Opened 2023-09-27 08:35 UTC by paulineheurtebise

Ajout slice sur l'id dans le slice sur l'url pour les actes spécifiques et les actes hors cabinets

2023-09-27 14:32 UTC, sdemeyANS requested changes
un warning dans sushi

2023-09-27 14:32 UTC, sdemeyANS commented on input/fsh/profiles/RORHealthcareService.fsh
> +* characteristic[act] ^slicing.discriminator[+].type = #value
un warn sushi warn  HealthcareService.characteristic[act]: An element with a slice name should not define its own slicing. Instead, append additional discriminators to the original slicing on the base element.
  File: /home/runner/work/IG-fhir-repertoire-offre-ressources-sante/IG-fhir-repertoire-offre-ressources-sante/ig/input/fsh/profiles/RORHealthcareService.fsh

2023-10-10 10:22 UTC, sdemeyANS commented on input/fsh/profiles/RORHealthcareService.fsh
> +* characteristic[act] ^slicing.discriminator[+].type = #value
@paulineheurtebise si c'est traité n'hésite pas à résoudre la conversation et à re-request ma review :)

2023-10-10 16:39 UTC, sdemeyANS commented
preview https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/97-determination-des-actes-sp%C3%A9cifiques-hors-cabinet/StructureDefinition-ror-healthcareservice.html

2023-10-10 16:47 UTC, sdemeyANS approved these changes

2023-10-11 07:12 UTC, nriss requested changes

2023-10-11 07:12 UTC, nriss commented on input/fsh/profiles/RORHealthcareService.fsh
> +* characteristic[careMode].coding.system from $JDV-J19-ModePriseEnCharge-ROR (required)
Est-ce normal que le system est bindé à un ValueSet ?
Ce ValueSet contient des URLs canoniques ?

2023-10-11 07:12 UTC, nriss commented on input/fsh/profiles/RORHealthcareService.fsh
> +* characteristic[receptionModality].coding.system from $JDV-J226-ModaliteAccueil-ROR (required)
idem

2023-10-11 07:12 UTC, nriss commented on input/fsh/profiles/RORHealthcareService.fsh
> +* characteristic ^slicing.discriminator[=].path = "coding.system"
A-t-on besoin des deux discriminator ?

2023-10-11 07:12 UTC, nriss commented on input/fsh/profiles/RORHealthcareService.fsh
> +* characteristic[receptionModality].id = "receptionModality"
Je ne pense pas qu'un champs multivalué puisse contenir le même id plusieurs fois

2023-10-11 08:56 UTC, sdemeyANS commented on input/fsh/profiles/RORHealthcareService.fsh
> +* characteristic[receptionModality].id = "receptionModality"
cf échange sur l'issue ? https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/issues/97#issuecomment-1730950787

2023-10-11 09:07 UTC, paulineheurtebise commented on input/fsh/profiles/RORHealthcareService.fsh
> +* characteristic[careMode].coding.system from $JDV-J19-ModePriseEnCharge-ROR (required)
tu as raison c'est un résidu qu'on aurait pas du laisser, je corrige avec un commit.

2023-10-11 09:10 UTC, paulineheurtebise commented on input/fsh/profiles/RORHealthcareService.fsh
> +* characteristic ^slicing.discriminator[=].path = "coding.system"
Au début l'idée était de slicer sur le bindig, sauf que 2 slices ont le meme JDV, donc nous avions convenu d'ajouter un slice sur l'id pour les différencier. 
Après c'est vrai qu'il est possible de faire que sur l'id.

2023-10-11 09:11 UTC, nriss commented on input/fsh/profiles/RORHealthcareService.fsh
> +* characteristic[receptionModality].id = "receptionModality"
JE pense que l'on ne s'est pas bien compris, ma crainte est que l'on peut avoir plusieurs fois la slice receptionModality étant donné que c'est de cardinalité 0..*
On aurait donc des slices différentes avec le même id, ce qui n'est pas possible : https://www.hl7.org/fhir/R4/element.html#id

2023-11-13 08:58 UTC, nriss requested changes
Il faut mettre à jour le discriminator

2023-11-14 14:05 UTC, sly-kereval commented on input/fsh/profiles/RORHealthcareService.fsh
> +* characteristic ^slicing.discriminator[=].path = "coding.system"
Cette solution a été abandonnée.

2023-11-14 14:06 UTC, sly-kereval commented on input/fsh/profiles/RORHealthcareService.fsh
> +* characteristic[receptionModality].id = "receptionModality"
L'utilisation de l'id comme discriminant a été abandonnée.

2023-11-14 14:10 UTC, sly-kereval commented
> Il faut mettre à jour le discriminator

@nriss actuellement dans notre proposition il y a 2 discriminants : coding.system et le type d'acte (extension), tu vois une autre façon de faire ?

2023-11-14 15:36 UTC, nriss approved these changes

2023-11-14 15:38 UTC, nriss commented
Je ne comprends pas je vois pas de commit mais ça me paraît bon maintenant, j'ai peut être mal lu la première fois
Merci :)

2023-11-14 16:18 UTC, sdemeyANS approved these changes

2023-11-14 16:22 UTC, merged