Ajout discriminant extensions de address.line de ror organization
ansforge/IG-fhir-repertoire-offre-ressources-sante pull request #133
Opened 2023-09-27 08:39 UTC by paulineheurtebise

Ajout slice sur id pour les extensions de meme url dans le slice sur l'url

2023-09-28 12:30 UTC, sdemeyANS requested changes
un warning sushi à traiter je pense

2023-09-28 12:30 UTC, sdemeyANS commented on input/fsh/profiles/ROROrganization.fsh
> +* address.line.extension[streetName] ^slicing.discriminator[+].type = #value
il y a un warning sushi comme pour la PR https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/pull/132
warn  Organization.address.line.extension[streetName]: An element with a slice name should not define its own slicing. Instead, append additional discriminators to the original slicing on the base element.
  File: /home/runner/work/IG-fhir-repertoire-offre-ressources-sante/IG-fhir-repertoire-offre-ressources-sante/input/fsh/profiles/ROROrganization.fsh
  Line: 1 - 211

2023-10-19 09:11 UTC, sdemeyANS commented
@paulineheurtebise pas de modif dans le fichier de mapping à faire en plus ?

2023-10-19 09:12 UTC, sdemeyANS requested changes
pas de modif à faire dans le fichier de mapping ?

2023-10-19 09:19 UTC, nriss approved these changes
Merci :)

2023-10-19 09:19 UTC, nriss commented on input/fsh/profiles/ROROrganization.fsh
> +* address.line.extension 0..*
Cette ligne me semble inutile, c'est la cardinalité par défaut

2023-10-20 08:39 UTC, paulineheurtebise commented
J'ai traité la maj du mapping dans la PR #154 avec toutes les autres évolutions.

2023-10-20 15:37 UTC, paulineheurtebise commented on input/fsh/profiles/ROROrganization.fsh
> +* address.line.extension 0..*
Ligne supprimée !

2023-10-23 07:48 UTC, sdemeyANS approved these changes

2023-10-23 07:49 UTC, sdemeyANS commented
il y a des conflits à résoudre

2023-10-31 08:37 UTC, merged