Correction syntaxe iterate
ansforge/IG-fhir-repertoire-offre-ressources-sante pull request #153
Opened 2023-10-18 15:15 UTC by paulineheurtebise

Cf #130 . 
correction de la syntaxe du iterate dans les requêtes exemples.

2023-10-19 09:09 UTC, sdemeyANS commented on input/pagecontent/specifications_techniques_2.md
> +GET [BASE]/HealthcareService?organization:above.identifier=XX&_include=HealthcareService:organization&_include:iterate=Organization:partof&_include=HealthcareService:location&_revinclude=Practitioner
peut être e,n profiter pour corriger above sur la même PR et lier la branche à l'issue https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/issues/150 ?

2023-10-19 09:15 UTC, sdemeyANS requested changes
peut être e,n profiter pour corriger above sur la même PR et lier la branche à l'issue https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/issues/150 ?

2023-10-19 09:25 UTC, sdemeyANS commented on input/pagecontent/specifications_techniques_2.md
> +GET [BASE]/HealthcareService?organization:above._lastUpdated=ge2022-11-06T15:00&organization.type= https://mos.esante.gouv.fr/NOS/TRE_R66-CategorieEtablissement/FHIR/TRE_R66-CategorieEtablissement|XX
above à vérifier

2023-10-19 09:26 UTC, sdemeyANS commented on input/pagecontent/specifications_techniques_2.md
> +GET [BASE]/HealthcareService?_filter=(_lastUpdated ge 2022-11-06T15:00 or organization:above._lastUpdated ge 2022-11-06T15:00) &_revinclude=Organization:healthcareservice&_include=HealthcareService:o
above à vérifier

2023-10-19 13:09 UTC, nriss commented on input/pagecontent/specifications_techniques_2.md
> +GET [BASE]/HealthcareService?organization:above._lastUpdated=ge2022-11-06T15:00&organization.type= https://mos.esante.gouv.fr/NOS/TRE_R66-CategorieEtablissement/FHIR/TRE_R66-CategorieEtablissement|XX
Il me semble que c'est bon, car on remonte la hiérarchie des organisations

2023-10-19 13:12 UTC, nriss approved these changes

2023-10-20 08:01 UTC, paulineheurtebise commented on input/pagecontent/specifications_techniques_2.md
> +GET [BASE]/HealthcareService?organization:above.identifier=XX&_include=HealthcareService:organization&_include:iterate=Organization:partof&_include=HealthcareService:location&_revinclude=Practitioner
Correction du above faite :)

2023-10-20 08:01 UTC, paulineheurtebise commented on input/pagecontent/specifications_techniques_2.md
> +GET [BASE]/HealthcareService?_filter=(_lastUpdated ge 2022-11-06T15:00 or organization:above._lastUpdated ge 2022-11-06T15:00) &_revinclude=Organization:healthcareservice&_include=HealthcareService:o
Correction du above faite :)

2023-10-20 08:47 UTC, sdemeyANS commented on input/pagecontent/specifications_techniques_2.md
> +GET [BASE]/HealthcareService?organization:above.identifier=XX&_include=HealthcareService:organization&_include:iterate=Organization:partof&_include=HealthcareService:location&_revinclude=Practitioner
Super ! merci ! D'une pierre deux coups :)

2023-10-20 08:49 UTC, sdemeyANS commented on input/pagecontent/specifications_techniques_2.md
> +GET [BASE]/HealthcareService?organization._lastUpdated:above=ge2022-11-06T15:00&organization.type= https://mos.esante.gouv.fr/NOS/TRE_R66-CategorieEtablissement/FHIR/TRE_R66-CategorieEtablissement|XX
@paulineheurtebise du coup c'était bien incorrect aussi ?

2023-10-20 09:04 UTC, paulineheurtebise commented on input/pagecontent/specifications_techniques_2.md
> +GET [BASE]/HealthcareService?organization._lastUpdated:above=ge2022-11-06T15:00&organization.type= https://mos.esante.gouv.fr/NOS/TRE_R66-CategorieEtablissement/FHIR/TRE_R66-CategorieEtablissement|XX
J'ai vérifié avec la spec et en faisant des tests sur HAPI, above était mal placé. J'ai corrigé partout.

2023-10-20 13:29 UTC, sdemeyANS approved these changes
merci :)

2023-10-20 13:30 UTC, merged