Ajout modificateur of-type
ansforge/IG-fhir-repertoire-offre-ressources-sante pull request #159
Opened 2023-11-02 13:44 UTC by paulineheurtebise

Ajout uniquement dans le narratif le modificateur of-type.

2023-11-02 16:21 UTC, sdemeyANS approved these changes
ok on modifiera les scenarios le cas échéant suite au retours de @jcserafini

2023-11-02 16:40 UTC, sdemeyANS requested changes
il ne faut pas aussi modifier le capability statment?

2023-11-03 09:21 UTC, paulineheurtebise commented
Bonne question, je n'avais pas pensé à vérifier. 
En regardant la ressource CS on met pas dedans les modificateurs de requêtes, je me trompe ?

2023-11-03 12:51 UTC, nriss commented
> Bonne question, je n'avais pas pensé à vérifier. En regardant la ressource CS on met pas dedans les modificateurs de requêtes, je me trompe ?

Je pense que c'est les SP qui renseignent les modifiers compatibles, et le CS renseigne les SP supportés
https://www.hl7.org/fhir/R4/searchparameter.html

2023-11-06 09:55 UTC, sdemeyANS commented
> > Bonne question, je n'avais pas pensé à vérifier. En regardant la ressource CS on met pas dedans les modificateurs de requêtes, je me trompe ?
> 
> Je pense que c'est les SP qui renseignent les modifiers compatibles, et le CS renseigne les SP supportés https://www.hl7.org/fhir/R4/searchparameter.html
> 
> <img alt="image" width="1187" src="https://user-images.githubusercontent.com/48218773/280283455-e7c689e9-9470-4783-970c-fd26bbc1891f.png">
> Preview de la branche : https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/99-pr%C3%A9ciser-le-type-didentifier-dans-une-recherche/modifiers.html


> > Bonne question, je n'avais pas pensé à vérifier. En regardant la ressource CS on met pas dedans les modificateurs de requêtes, je me trompe ?
> 
> Je pense que c'est les SP qui renseignent les modifiers compatibles, et le CS renseigne les SP supportés https://www.hl7.org/fhir/R4/searchparameter.html
> 
> <img alt="image" width="1187" src="https://user-images.githubusercontent.com/48218773/280283455-e7c689e9-9470-4783-970c-fd26bbc1891f.png">
> Preview de la branche : https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/99-pr%C3%A9ciser-le-type-didentifier-dans-une-recherche/modifiers.html

OK donc on laisse que dans le narratif vu que le SP est natif "identifier". Il faudra se poser peut être la question sur les SP "non-natif"

2023-11-06 09:56 UTC, sdemeyANS approved these changes
ok. voir discussion :)

2023-11-06 09:58 UTC, nriss approved these changes

2023-11-07 07:47 UTC, merged