172 ajout scenarios ig
ansforge/IG-fhir-repertoire-offre-ressources-sante pull request #179
Opened 2023-11-14 14:31 UTC by paulineheurtebise

Ajout scénario 1bis - Recherche sur une région
Retrait des Réponses simplifiées sur la page consultation des données capacitaires (plus de sens dans le format IG et uniformisation avec les autres pages)
Correction critère de recherche providedBy -> organization

2023-11-14 14:59 UTC, sdemeyANS requested changes
il faut ajouter le scenario 1 bis dans spec fontionnelles aussi du coup il  me semble

2023-11-14 18:25 UTC, sdemeyANS commented
> Ajout scénario 1bis - Recherche sur une région Retrait des Réponses simplifiées sur la page consultation des données capacitaires (plus de sens dans le format IG et uniformisation avec les autres pages) Correction critère de recherche providedBy -> organization

si suppression des réponses simplifiées suppression aussi de https://interop.esante.gouv.fr/ig/fhir/ror/annexes.html ?

2023-11-14 18:26 UTC, sdemeyANS requested changes

2023-11-14 18:26 UTC, sdemeyANS commented on input/pagecontent/specifications_techniques_1.md
> -**Réponse "simplifiée" :**
pour être cohérent il faut aussi supprimer https://interop.esante.gouv.fr/ig/fhir/ror/annexes.html dans ce cas ?

2023-11-17 10:10 UTC, paulineheurtebise commented on input/pagecontent/specifications_techniques_1.md
> -**Réponse "simplifiée" :**
ah c'est que je ne retrouvais plus la page donc ca n'avait plus de sens. 
Effectivement avec la source, je ne doit pas les supprimer.

2023-11-20 14:26 UTC, sdemeyANS commented
@jcserafini et @PhilippeC-ANS pour info la preview est ici https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/172-ajout-scenarios-ig/specifications_techniques_1.html . Est-ce que cela vous convient ?

2023-11-20 17:42 UTC, sdemeyANS commented
@PhilippeC-ANS et @jcserafini  la description du scenario stipule :
**Description du scénario :** un consommateur souhaite récupérer l\'ensemble des données capacitaires sur une région afin de mettre à jour son système. Par exemple en Bretagne qui est composé des départements 22,29,35,56. 
Du coup Pauline propose une recherche sur la liste des départements. Est-ce bien votre attente ou voulez vous passer par le code 
 Region ?

2023-11-21 08:29 UTC, nriss approved these changes
Ok pour moi sur la partie technique :)

2023-11-28 10:23 UTC, sdemeyANS commented
> @PhilippeC-ANS et @jcserafini la description du scenario stipule : **Description du scénario :** un consommateur souhaite récupérer l'ensemble des données capacitaires sur une région afin de mettre à jour son système. Par exemple en Bretagne qui est composé des départements 22,29,35,56. Du coup Pauline propose une recherche sur la liste des départements. Est-ce bien votre attente ou voulez vous passer par le code Region ?

@RomainCaraty également pour info/avis merci :)

2023-11-29 12:59 UTC, PhilippeC-ANS commented
@sdemeyANS Je te confirme que la logique de ce cas d'usage est bien de s'appuyer sur les départements liés à l'adresse de l'EG, et pas sur le code de la région source des données.
La proposition Kereval me semble donc OK

2023-11-29 13:06 UTC, sdemeyANS commented
> @sdemeyANS Je te confirme que la logique de ce cas d'usage est bien de s'appuyer sur les départements liés à l'adresse de l'EG, et pas sur le code de la région source des données. La proposition Kereval me semble donc OK

Merci pour ce retour. On valide donc ce changement

2023-11-29 13:06 UTC, sdemeyANS approved these changes
suite au retour du ROR

2023-11-30 07:16 UTC, merged

2023-12-07 13:52 UTC, RomainCaraty commented
Bonjour @sdemeyANS,

Comme vu ensemble il faut que le scénario 1 de consultation des données capacitaires apparaissent sur l'IG avec l'exemple suivant : 

►	Scénario 1 : Données capacitaires sur le périmètre régional
•	Un consommateur souhaite récupérer l'ensemble des données capacitaires sur le périmètre régional afin de mettre à jour son système
Exemple : récupération des données capacitaires pour la région « 52 – Pays de la Loire »

Requête : https://api.rortest.esante.gouv.fr/ws-diffusion-fhir/Location?_revinclude=HealthcareService:location&_tag=52

2023-12-07 13:55 UTC, nriss commented
Cette PR est merge, il vaut mieux créer une nouvelle issue pour tracer dans le workflow