Correction typo espaces
ansforge/IG-fhir-repertoire-offre-ressources-sante pull request #189
Opened 2023-11-17 10:08 UTC by sly-kereval

Correction des espaces en trop dans les exemples de requêtes

2023-11-23 14:28 UTC, nriss approved these changes

2023-11-23 14:52 UTC, nriss commented on input/pagecontent/specifications_techniques_2.md
> +&organization.type=https ://mos.esante.gouv.fr/NOS/TRE_R66-CategorieEtablissement/FHIR/TRE_R66-CategorieEtablissement|XXX #critère de recherche sur la categorieEG (nomenclature à compléter)
```suggestion
&organization.type=https://mos.esante.gouv.fr/NOS/TRE_R66-CategorieEtablissement/FHIR/TRE_R66-CategorieEtablissement|XXX #critère de recherche sur la categorieEG (nomenclature à compléter)
```

2023-11-23 14:53 UTC, nriss commented on input/pagecontent/specifications_techniques_4.md
> +`GET [BASE]/HealthcareService?specialty=https://mos.esante.gouv.fr/NOS/TRE_R211-ActiviteOperationnelle/FHIR/TRE-R211-ActiviteOperationnelle|025&location:equipment-type=https://mos.esante.gouv.fr/NOS/
A quoi correspond ce sp location:equipment-type ? C'est un slice-name ?

2023-11-23 14:57 UTC, sdemeyANS requested changes

2023-11-23 14:57 UTC, sdemeyANS commented on input/pagecontent/specifications_techniques_2.md
> +&organization.type=https ://mos.esante.gouv.fr/NOS/TRE_R66-CategorieEtablissement/FHIR/TRE_R66-CategorieEtablissement|XXX #critère de recherche sur la categorieEG (nomenclature à compléter)
typo espace https

2023-11-24 08:37 UTC, sdemeyANS commented on input/pagecontent/specifications_techniques_2.md
> +GET [BASE]/HealthcareService?_filter=(_lastUpdated ge 2022-11-06T15:00 or organization._lastUpdated:above ge 2022-11-06T15:00)&_revinclude=Organization:healthcareservice&_include=HealthcareService:or
@paulineheurtebise et @sly-kereval pour info

2023-11-24 08:41 UTC, sdemeyANS approved these changes
ok pour les espaces @sly-kereval  mais il reste la question de @nriss https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/pull/189#discussion_r1403486143

2023-11-27 09:44 UTC, paulineheurtebise commented on input/pagecontent/specifications_techniques_2.md
> +GET [BASE]/HealthcareService?_filter=(_lastUpdated ge 2022-11-06T15:00 or organization._lastUpdated:above ge 2022-11-06T15:00)&_revinclude=Organization:healthcareservice&_include=HealthcareService:or
Nous avons regardé la spec de above en R5/6 il y a un monde avec R4. 
A l'époque en plus nous ne pouvions pas le tester avec HAPI. 
Tu as raison Nicolas, il est bien précisé en R5 que above s'applique uniquement à des types reference, uri, token. donc pas à une date et nous n'arrivons pas à trouver une syntaxe permettant de répondre au besoin. Peut etre ouvrir une issue spécifique ?

2023-11-27 12:11 UTC, nriss commented on input/pagecontent/specifications_techniques_2.md
> +GET [BASE]/HealthcareService?_filter=(_lastUpdated ge 2022-11-06T15:00 or organization._lastUpdated:above ge 2022-11-06T15:00)&_revinclude=Organization:healthcareservice&_include=HealthcareService:or
Ok pour l'issue :)

Peux-tu rappeler le besoin fonctionnel de la requête en la simplifiant au maximum avec le search param _lastUpdated ?

2023-11-27 15:49 UTC, paulineheurtebise commented on input/pagecontent/specifications_techniques_2.md
> +GET [BASE]/HealthcareService?_filter=(_lastUpdated ge 2022-11-06T15:00 or organization._lastUpdated:above ge 2022-11-06T15:00)&_revinclude=Organization:healthcareservice&_include=HealthcareService:or
Le besoin de cette requête est de rechercher les healthcarService dont l'organization ou une des organization parentes a été mis à jour depuis une certaine date. 
Par exemple, on veut que les healthcareService, dont le pole ou l'EG ou l'EJ a été mis à jour depuis le mois dernier

2023-11-28 10:28 UTC, sdemeyANS commented
@paulineheurtebise et @sly-kereval ok pour le merge donc merci :)

2023-11-28 15:13 UTC, merged