correction scenario 2 consultation Ano
ansforge/IG-fhir-repertoire-offre-ressources-sante pull request #223
Opened 2023-12-12 15:59 UTC by sdemeyANS

correction erreur transcription docx vers IG sur scenario 2 consultation Ano
preview correction https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/sd-correction-scenario-2-consultation-ano/specifications_techniques_7.html#sc%C3%A9nario-2-consultation-de-la-liste-des-anomalies

2023-12-14 17:30 UTC, sly-kereval requested changes

2023-12-14 17:30 UTC, sly-kereval commented on input/pagecontent/specifications_techniques_7.md
> +**Description du scénario :** Un responsable qualité où le moteur de règle souhaite consulter la liste des anomalies d'un élément dont l’identifiant est XXX.
"ou" à la place "où"

2023-12-14 17:40 UTC, sdemeyANS commented on input/pagecontent/specifications_techniques_7.md
> +**Description du scénario :** Un responsable qualité où le moteur de règle souhaite consulter la liste des anomalies d'un élément dont l’identifiant est XXX.
provenait du docx ;)
C'est corrigé

2023-12-15 07:05 UTC, sly-kereval approved these changes

2023-12-15 08:11 UTC, merged