Ajout cas usage saisie offre
ansforge/IG-fhir-repertoire-offre-ressources-sante pull request #230
Opened 2023-12-15 17:17 UTC by paulineheurtebise

Version draft pour revue : https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/203-ajout-cas-usage-saisie-offre/

1. Pour le cas d’usage de création, la mention [spécifique serveur] a été ajoutée devant le titre des scénarios
--> Réfléchir à une harmonisation avec les acteurs des diagrammes de séquences ? + valider les acteurs
2. Les schémas de la partie SF ont été réalisés en plantuml (plus facile à maintenir et plus uniforme) pour les nouveaux cas d’usage 
--> @sdemeyANS est ce que c’est ok ?
3. Scénarios MaJ 5 et 8. Concernant les requêtes patch dans le cas de l’ajout de plusieurs éléments dans un tableau (élément multivalué), la syntaxe proposée actuellement fonctionne mais il reste à voir s’il est possible de la condenser. 
4. Maj scénario 7 (ligne 83 excel) : Le scénario de retrait d’une activité opérationnelle (suppression) est-il à conserver ? 
--> @PhilippeC-ANS on conserve le scénario ?
5. MaJ scénario 4 (Modification d'informations sur un professionnel, ligne 87 excel) : Comme l’élément telecom est multivalué, le seul moyen d’identifier l’adresse MSS à modifier est de mettre un critère sur l’ancienne valeur (telecom.value) 
--> Réflexion sur une autre façon d’identification ?
6. Maj scénario 1 (Modification d'une entité juridique, ligne 88 excel) : Actuellement, la cardinalité de Organization.address est 0..* mais d’après le ME (adresseEJ), elle doit être 0..1. 
L’exemple de requête fonctionne dans le cas où la cardinalité est 0..1 puisque sinon il faut identifier l’adresse à modifier. 
--> @PhilippeC-ANS on est d'accord qu'il y a bien qu'une adresse pour chaque organisation ? 
--> si oui Issue à créer. (impact dev à demander à @jcserafini )
7. MaJ scénario 2 (Modification d'une entité géographique, ligne 89 excel) : Pour le moment on a considéré que l’on connait l’ancien numéro de téléphone car sinon il ne semble pas possible d’identifier quelle instance de telecom modifier.
--> @sdemeyANS ou @jcserafini Est ce que c'est un problème de se baser sur l'ancien numéro de téléphone ? 
8. Maj scénario 8 (Précision sur l'offre opérationnelle d'un cabinet de ville, ligne 85 excel) : Pour le moment dans l’exemple de requête il y a un seul horaire alors qu’il y en a 2 dans le excel car la cardinalité de availableTime ne le permet à Issue à créer ou compléter la #221

2023-12-21 11:12 UTC, sdemeyANS commented
@paulineheurtebise 
OK pour 

> 2. Les schémas de la partie SF ont été réalisés en plantuml (plus facile à maintenir et plus uniforme) pour les nouveaux cas d’usage
> --> @sdemeyANS est ce que c’est ok ?

Mais du coup il faudra refaire les autres pour être uniforme

2023-12-21 20:35 UTC, PhilippeC-ANS commented on input/pagecontent/specifications_techniques_12.md
> +            "system": "http://sirene.fr"
même question

2023-12-21 20:35 UTC, PhilippeC-ANS commented on input/pagecontent/specifications_techniques_12.md
> +            "system": "https://mos.esante.gouv.fr/NOS/JDV_J55-CategorieEG-ROR/FHIR/JDV-J55-CategorieEG-ROR",
On n'expose pas l'adresse de la TRE qui est derrière le JDV ?

2023-12-21 20:35 UTC, PhilippeC-ANS commented on input/pagecontent/specifications_techniques_12.md
> +			"valueBoolean": true
c'est du détail, mais le "0" se transforme en "true" en FHIR ?

2023-12-21 20:35 UTC, PhilippeC-ANS commented on input/pagecontent/specifications_techniques_12.md
> +			"valueDateTime": "2023-12"
c'est le bon format pour la date de création ? Je pensais que l'on était + précis que année-mois

2023-12-21 20:35 UTC, PhilippeC-ANS commented on input/pagecontent/specifications_techniques_12.md
> +			"valueDateTime": "2023-12"
même remarque

2023-12-21 20:35 UTC, PhilippeC-ANS commented on input/pagecontent/specifications_techniques_12.md
> +            "system": "urn:oid:1.2.250.1.71.4.2.2"
à quoi correspond cet OID ?

2023-12-21 20:35 UTC, PhilippeC-ANS commented on input/pagecontent/specifications_techniques_12.md
>  #### Scénario 3 : Création de l'organisation interne d'un établissement
Pour moi ce scénario n'est pas "spécifique serveur" (à confirmer avec l'équipe technique ?)

2023-12-21 20:35 UTC, PhilippeC-ANS commented on input/pagecontent/specifications_techniques_12.md
> +        "reference": "Organization/idEJ"
Comment récupère-t-il l'id à utiliser ?
Peut-il enchainer création EJ et EG ou doit-il exploiter le message de réponse de la création de l'EJ pour obtenir l'id de l'EJ et ensuite créer l'EG ?

2023-12-21 20:35 UTC, PhilippeC-ANS commented on input/pagecontent/specifications_techniques_12.md
> +        "reference": "Organization/id"
pourquoi ne précise-t-on pas ici que c'est l'id de l'EG ?

2023-12-21 20:35 UTC, PhilippeC-ANS commented on input/pagecontent/specifications_techniques_12.md
> +            "system": "http://interopsante.org/fhir/CodeSystem/fr-v2-3307",
On ne s'appuie pas sur le JDV ou la TRE des typeOi ?

2023-12-21 20:35 UTC, PhilippeC-ANS commented on input/pagecontent/specifications_techniques_12.md
>  #### Scénario 3 : Création de l'organisation interne d'un établissement
Il me semble qu'il y a un écart entre la restitution sur https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/203-ajout-cas-usage-saisie-offre/specifications_techniques_12.html (scenario 4) et cette page (scenario 3)

2023-12-21 20:35 UTC, PhilippeC-ANS commented on input/pagecontent/specifications_techniques_12.md
> +                "system": "https://mos.esante.gouv.fr/NOS/TRE_R345-TypeIdentifiantAutre/FHIR/TRE_R345-TypeIdentifiantAutre"
j'ai du mal à suivre si on doit exposer des url de TRE ou de JDV

2023-12-21 20:35 UTC, PhilippeC-ANS commented on input/pagecontent/specifications_techniques_12.md
> +        "system": "https://oi.esante.gouv.fr"
à quoi correspond cette page ?

2023-12-21 20:35 UTC, PhilippeC-ANS commented on input/pagecontent/specifications_techniques_12.md
> +#### Scénario 4 : Création d'une offre dans une unité fonctionnelle préexistante
Je ne trouve pas la suite du détail : suis-je au bon endroit pour commenter ?

2023-12-21 20:38 UTC, PhilippeC-ANS commented
> 4\. Maj scénario 7 (ligne 83 excel) : Le scénario de retrait d’une activité opérationnelle (suppression) est-il à conserver ?
>     --> @PhilippeC-ANS on conserve le scénario ?

Pour moi oui : Nous allons avoir un certain nombre de cas où une AO va être supprimée (notamment les AO qui seront choisies par défaut lors d'un adossement) => Il me semble intéressant de l'illustrer

2023-12-21 20:42 UTC, PhilippeC-ANS commented
> 6\. Maj scénario 1 (Modification d'une entité juridique, ligne 88 excel) : Actuellement, la cardinalité de Organization.address est 0..* mais d’après le ME (adresseEJ), elle doit être 0..1.
>     L’exemple de requête fonctionne dans le cas où la cardinalité est 0..1 puisque sinon il faut identifier l’adresse à modifier.
>     --> @PhilippeC-ANS on est d'accord qu'il y a bien qu'une adresse pour chaque organisation ?
>     --> si oui Issue à créer. (impact dev à demander à @jcserafini )

Si la question est : une EJ n'a t-elle qu'une adresse, la réponse est oui. Cette réponse vaut également pour l'EG : chaque EG n'a qu'une seule adresse.
Par contre une EJ (avec 1 seule adresse) peut être parente de plusieurs EG (avec chacune une adresse différente).

2023-12-21 20:45 UTC, PhilippeC-ANS commented
Sur la page https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/203-ajout-cas-usage-saisie-offre/specifications_techniques_12.html tous les scénarios apparaissent comme "spécifique serveur".
Il me semble que cela ne devrait concerner que les créations d'EJ et d'EG.
@jcserafini es-tu en phase avec ce propos ?

2024-01-08 12:33 UTC, sly-kereval commented on input/pagecontent/specifications_techniques_12.md
> +            "system": "https://mos.esante.gouv.fr/NOS/JDV_J55-CategorieEG-ROR/FHIR/JDV-J55-CategorieEG-ROR",
En effet c'était une erreur, c'est corrigé (JDV J55 remplacé par la TRE R66).

2024-01-08 12:35 UTC, sly-kereval commented on input/pagecontent/specifications_techniques_12.md
> +            "system": "http://sirene.fr"
Des explications à ce sujet sont données dans l'issue #233, n'hésitez pas à commenter à nouveau si ce n'est pas suffisant.

2024-01-08 12:36 UTC, sly-kereval commented on input/pagecontent/specifications_techniques_12.md
> +            "system": "http://sirene.fr"
Idem que plus haut, des explications à ce sujet sont données dans l'issue #233, n'hésitez pas à commenter à nouveau si ce n'est pas suffisant.

2024-01-08 12:38 UTC, sly-kereval commented on input/pagecontent/specifications_techniques_12.md
> +			"valueBoolean": true
En effet en FHIR les valeurs possibles pour le type de données [boolean](https://hl7.org/fhir/R4/datatypes.html#boolean) sont true et false. Nous avons associé une valeur arbitraire au 0 présent dans le excel (true), il est possible de modifier si c'est l'inverse.

2024-01-08 12:40 UTC, sly-kereval commented on input/pagecontent/specifications_techniques_12.md
> +			"valueDateTime": "2023-12"
Le format FHIR [dateTime](https://hl7.org/fhir/R4/datatypes.html#dateTime) requiert de renseigner au moins l'année mais il permet aussi d'être plus précis comme indiqué dans la documentation. On peut préciser la valeur dans l'exemple de requête si besoin.

2024-01-08 12:43 UTC, sly-kereval commented on input/pagecontent/specifications_techniques_12.md
> +			"valueDateTime": "2023-12"
Même réponse que plus haut : Le format FHIR [dateTime](https://hl7.org/fhir/R4/datatypes.html#dateTime) requiert de renseigner au moins l'année mais il permet aussi d'être plus précis comme indiqué dans la documentation. On peut préciser la valeur dans l'exemple de requête si besoin.

2024-01-08 12:45 UTC, sly-kereval commented on input/pagecontent/specifications_techniques_12.md
> +            "system": "urn:oid:1.2.250.1.71.4.2.2"
Provient du traitement de l'issue #83

2024-01-08 12:51 UTC, sly-kereval commented on input/pagecontent/specifications_techniques_12.md
>  #### Scénario 3 : Création de l'organisation interne d'un établissement
Cette précision a été ajoutée.

2024-01-08 12:58 UTC, sly-kereval commented on input/pagecontent/specifications_techniques_12.md
> +                "system": "https://mos.esante.gouv.fr/NOS/TRE_R345-TypeIdentifiantAutre/FHIR/TRE_R345-TypeIdentifiantAutre"
Il faut exposer les urls des TRE, il y a eu des erreurs dans une première version des spécifications du cas d'usage de saisie de l'offre mais elles sont corrigées.

2024-01-08 12:59 UTC, sly-kereval commented on input/pagecontent/specifications_techniques_12.md
> +        "system": "https://oi.esante.gouv.fr"
Explications données dans l'issue #233, n'hésitez pas à commenter à nouveau si ce n'est pas suffisant.

2024-01-08 13:00 UTC, sly-kereval commented on input/pagecontent/specifications_techniques_12.md
> +#### Scénario 4 : Création d'une offre dans une unité fonctionnelle préexistante
Ce scénario ne devait pas être complet au moment de la review, ça devrait être le cas maintenant.

2024-01-08 13:03 UTC, sly-kereval commented on input/pagecontent/specifications_techniques_12.md
>  #### Scénario 3 : Création de l'organisation interne d'un établissement
Des modifications étaient probablement en cours au moment de la review, ça devrait être bon maintenant.

2024-01-08 13:18 UTC, paulineheurtebise commented on input/pagecontent/specifications_techniques_12.md
> +        "reference": "Organization/idEJ"
> Peut-il enchainer création EJ et EG ou doit-il exploiter le message de réponse de la création de l'EJ pour obtenir l'id de l'EJ et ensuite créer l'EG ?

Ce sont des opérations unitaires donc pour créer l'EG et l'EJ on fait 2 appels. 
L'EJ doit etre créée en premier, c'est un pré-requis à la création de l'EG. 

> Comment récupère-t-il l'id à utiliser ?
Plusieurs solutions, je ne sais pas ce qui sera privilégié.

2024-01-08 15:34 UTC, sly-kereval commented
> > 6. Maj scénario 1 (Modification d'une entité juridique, ligne 88 excel) : Actuellement, la cardinalité de Organization.address est 0..* mais d’après le ME (adresseEJ), elle doit être 0..1.
> > L’exemple de requête fonctionne dans le cas où la cardinalité est 0..1 puisque sinon il faut identifier l’adresse à modifier.
> > --> @PhilippeC-ANS on est d'accord qu'il y a bien qu'une adresse pour chaque organisation ?
> > --> si oui Issue à créer. (impact dev à demander à @jcserafini )
> 
> Si la question est : une EJ n'a t-elle qu'une adresse, la réponse est oui. Cette réponse vaut également pour l'EG : chaque EG n'a qu'une seule adresse. Par contre une EJ (avec 1 seule adresse) peut être parente de plusieurs EG (avec chacune une adresse différente).

Merci pour ces informations, une issue a été créée : #274

2024-01-08 15:50 UTC, sdemeyANS commented on input/pagecontent/specifications_techniques_12.md
> +        "system": "https://oi.esante.gouv.fr"
voir issue d'origine #83

2024-01-09 11:44 UTC, PhilippeC-ANS commented on input/pagecontent/specifications_techniques_12.md
> +            "system": "http://sirene.fr"
OK, conforme à la conclusion du ticket #83

2024-01-09 11:45 UTC, PhilippeC-ANS commented on input/pagecontent/specifications_techniques_12.md
> +            "system": "http://sirene.fr"
OK, conforme à la conclusion du ticket https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/issues/83

2024-01-09 11:48 UTC, PhilippeC-ANS commented on input/pagecontent/specifications_techniques_12.md
> +            "system": "https://mos.esante.gouv.fr/NOS/JDV_J55-CategorieEG-ROR/FHIR/JDV-J55-CategorieEG-ROR",
@sdemeyANS je n'arrive pas à visualiser la correction (le lien hypertext du message précédent contient toujours la référence au JDV) : où dois-je regarder ?

2024-01-09 11:51 UTC, PhilippeC-ANS commented on input/pagecontent/specifications_techniques_12.md
> +			"valueBoolean": true
@sly-kereval effectivement dans la logique le 0 devrait être traduit en "false" et le 1 en "true"

2024-01-09 11:54 UTC, PhilippeC-ANS commented on input/pagecontent/specifications_techniques_12.md
> +			"valueDateTime": "2023-12"
@sly-kereval il me semble préférable dans l'exemple de faire figurer le format demandé dans le modèle d'exposition (incluant HH:MM:SS), cf. RG_EXP_030

2024-01-09 11:54 UTC, PhilippeC-ANS commented on input/pagecontent/specifications_techniques_12.md
> +			"valueDateTime": "2023-12"
@sly-kereval il me semble préférable dans l'exemple de faire figurer le format demandé dans le modèle d'exposition (incluant HH:MM:SS), cf. RG_EXP_030

2024-01-09 11:55 UTC, PhilippeC-ANS commented on input/pagecontent/specifications_techniques_12.md
> +            "system": "urn:oid:1.2.250.1.71.4.2.2"
OK

2024-01-09 11:58 UTC, PhilippeC-ANS commented on input/pagecontent/specifications_techniques_12.md
> +        "reference": "Organization/idEJ"
OK

2024-01-09 12:01 UTC, PhilippeC-ANS commented on input/pagecontent/specifications_techniques_12.md
> +                "system": "https://mos.esante.gouv.fr/NOS/TRE_R345-TypeIdentifiantAutre/FHIR/TRE_R345-TypeIdentifiantAutre"
OK

2024-01-09 12:01 UTC, PhilippeC-ANS commented on input/pagecontent/specifications_techniques_12.md
> +        "system": "https://oi.esante.gouv.fr"
OK

2024-01-09 13:22 UTC, sly-kereval commented on input/pagecontent/specifications_techniques_12.md
> +			"valueBoolean": true
D'accord, ça sera pris en compte dans un prochain commit.

2024-01-09 13:37 UTC, sly-kereval commented on input/pagecontent/specifications_techniques_12.md
> +			"valueDateTime": "2023-12"
D'accord, ça sera pris en compte dans un prochain commit.

2024-01-12 13:47 UTC, sdemeyANS commented on input/pagecontent/specifications_fonctionnelles.md
> +        <td align ="center">
problème de mise en page https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/203-ajout-cas-usage-saisie-offre/specifications_fonctionnelles.html#description-du-cas-dusage-1 cela nécessite de scroller

2024-01-12 13:53 UTC, sdemeyANS commented on input/pagecontent/specifications_fonctionnelles.md
> +Un serveur souhaite créer une offre.
Est-ce que l'on doit préciser ici que le serveur = ROR National. Ici on peut peut être interprété que n'importe quel serveur peut le créer. @jcserafini et @ MDC ? Qu'en pensez-vous ?

2024-01-15 08:02 UTC, sly-kereval commented on input/pagecontent/specifications_fonctionnelles.md
> +        <td align ="center">
C'est corrigé

2024-01-15 11:15 UTC, jcserafini commented
Hello
A la relecture on se rend compte que le scénario de modification d'une offre sur de multiples informations aurait du sens, en particulier coté IHM ou on va certainement effectuer les modifications en bloc sur base de ce qui a été modifié par l'utilisateur:
Exemple:
L'utilisateur a ajouté 1 activités opérationnelles + ajout 1 acte spé + ajout un contact avec son numéro + modifie ses horaires et valide la saisie -> dans ce cas vaut il mieux faire n PATCH ou 1 seul PUT avec toutes les infos ?

2024-01-23 13:49 UTC, sdemeyANS commented on input/pagecontent/specifications_techniques_13.md
> +**Requête :** Voir [scénario 10 du cas d'usage saisie de l'offre](specifications_techniques_12.html#spécifique-serveur-scénario-10-création-dune-situation-opérationnelle) (Création d'une situation op
est-ce que c'est assez compréhensible que ce scenario 9 = scenario 10 de specifications_techniques_12.html#spécifique-serveur-scénario-10-création-dune-situation-opérationnelle ?

2024-01-23 13:51 UTC, sdemeyANS requested changes
A vérifier les capability statment

2024-01-25 08:10 UTC, paulineheurtebise commented on input/pagecontent/specifications_techniques_12.md
> +			"valueDateTime": "2023-12"
Corrigé preview : [https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/203-ajout-cas-usage-saisie-offre/specifications_techniques_12.html#sp%C3%A9cifique-serveur-sc%C3%A9nario-1-cr%C3%A9ation-de-lentit%C3%A9-juridique](https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/203-ajout-cas-usage-saisie-offre/specifications_techniques_12.html#sp%C3%A9cifique-serveur-sc%C3%A9nario-1-cr%C3%A9ation-de-lentit%C3%A9-juridique)

2024-01-25 08:12 UTC, paulineheurtebise commented on input/pagecontent/specifications_techniques_12.md
> +            "system": "https://mos.esante.gouv.fr/NOS/JDV_J55-CategorieEG-ROR/FHIR/JDV-J55-CategorieEG-ROR",
Corrigé preview : [https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/203-ajout-cas-usage-saisie-offre/specifications_techniques_12.html#sp%C3%A9cifique-serveur-sc%C3%A9nario-2-cr%C3%A9ation-de-lentit%C3%A9-g%C3%A9ographique](https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/203-ajout-cas-usage-saisie-offre/specifications_techniques_12.html#sp%C3%A9cifique-serveur-sc%C3%A9nario-2-cr%C3%A9ation-de-lentit%C3%A9-g%C3%A9ographique)

2024-01-25 08:13 UTC, paulineheurtebise commented on input/pagecontent/specifications_techniques_12.md
> +			"valueDateTime": "2023-12"
Corrigé preview : [https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/203-ajout-cas-usage-saisie-offre/specifications_techniques_12.html#sp%C3%A9cifique-serveur-sc%C3%A9nario-2-cr%C3%A9ation-de-lentit%C3%A9-g%C3%A9ographique](https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/203-ajout-cas-usage-saisie-offre/specifications_techniques_12.html#sp%C3%A9cifique-serveur-sc%C3%A9nario-2-cr%C3%A9ation-de-lentit%C3%A9-g%C3%A9ographique)

2024-01-25 08:14 UTC, paulineheurtebise commented on input/pagecontent/specifications_techniques_12.md
> +			"valueBoolean": true
Corrigé preview : [https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/203-ajout-cas-usage-saisie-offre/specifications_techniques_12.html#sp%C3%A9cifique-serveur-sc%C3%A9nario-2-cr%C3%A9ation-de-lentit%C3%A9-g%C3%A9ographique](https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/203-ajout-cas-usage-saisie-offre/specifications_techniques_12.html#sp%C3%A9cifique-serveur-sc%C3%A9nario-2-cr%C3%A9ation-de-lentit%C3%A9-g%C3%A9ographique)

2024-01-25 08:15 UTC, paulineheurtebise commented on input/pagecontent/specifications_techniques_12.md
> +        "reference": "Organization/id"
Corrigé preview : [https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/203-ajout-cas-usage-saisie-offre/specifications_techniques_12.html#sp%C3%A9cifique-serveur-sc%C3%A9nario-3-cr%C3%A9ation-dune-offre-op%C3%A9rationnelle-directement-rattach%C3%A9e-%C3%A0-l%C3%A9tablissement](https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/203-ajout-cas-usage-saisie-offre/specifications_techniques_12.html#sp%C3%A9cifique-serveur-sc%C3%A9nario-3-cr%C3%A9ation-dune-offre-op%C3%A9rationnelle-directement-rattach%C3%A9e-%C3%A0-l%C3%A9tablissement)

2024-01-25 08:40 UTC, paulineheurtebise commented on input/pagecontent/specifications_techniques_12.md
> +#### Scénario 4 : Création d'une offre dans une unité fonctionnelle préexistante
Preview : [https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/203-ajout-cas-usage-saisie-offre/specifications_techniques_12.html#sp%C3%A9cifique-serveur-sc%C3%A9nario-4-cr%C3%A9ation-dun-p%C3%B4le](https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/203-ajout-cas-usage-saisie-offre/specifications_techniques_12.html#sp%C3%A9cifique-serveur-sc%C3%A9nario-4-cr%C3%A9ation-dun-p%C3%B4le)

2024-01-26 10:19 UTC, paulineheurtebise commented
Réunion du 25/01/24 : 

- Serveur = serveur FHIR ROR National 
   - [ ] Préciser dans le narratif qui est serveur 
   - [ ] Ajouter une phrase dans les scénarios  pour préciser le tag Serveur : " 

- Les scénarios de création de toutes les ressources sont uniquement applicable au serveur --> narratif + CS
   - [ ] Maj CS 
   - [ ] Reprendre les scénarios Location pour ajouter la mention spécifique serveur

- Les scénarios de mise à jour de toutes les ressources sont uniquement applicable au serveur --> narratif + CS
Exception scénario bed management + ajout d'une location à un healthcareService
   - [ ] Maj CS 
   - [ ] Reprendre les scénarios Location pour ajouter la mention spécifique serveur

- Scénario maj :  
   - [ ] Scénario 4 maj : Modifier le scénario pour mettre à jour tout le bloc telecom
   - [ ] Scénario 8 maj : Modifier le scénario pour mettre à jour tout le bloc telecom
   - [ ] Préciser dans le narratif que seuls les attributs "1er niveau" peuvent etre maj
   - [ ] Préciser dans le CS que seuls les attributs "1er niveau" peuvent etre maj

- Ajout d'un scénario de mise à jour avec PUT
   - [ ] Ajout scénario cf. demande de Jean-Claude
   - [ ] Modification du CS

- Ajout scénario PATCH 
   - [ ] Ajout scénario ajout d'une Location à un HealthcareService

- Issue #221 : privilégier si possible l'usage de l'attribut natif, mais c'est une modification du format (impact sur le ME)
   - [ ] Mail à Matthieu à faire pour valider l'utilisation de l'attribut natif et les impacts

2024-01-26 13:32 UTC, paulineheurtebise commented on input/pagecontent/specifications_techniques_12.md
> +            "system": "http://interopsante.org/fhir/CodeSystem/fr-v2-3307",
Merci Philippe d'avoir soulevé ce point. 

Dans la ressource ROROrganization, le JDV associé au type d'organisation est un JDV InteropSanté [fr-organization-type](https://simplifier.net/packages/hl7.fhir.fr.core/1.1.0/files/783673). 
ROROrganization hérite de FrOrganization qui impose l'utilisation du JDV InteropSanté

A l'exception du code "unité élémentaire" toutes les valeurs du [JDV_J203-TypeOrganisationInterne-ROR](https://mos.esante.gouv.fr/NOS/JDV_J203-TypeOrganisationInterne-ROR/JDV_J203-TypeOrganisationInterne-ROR.pdf) se retrouvent dans le JDV Interop. 

Est ce qu'il entendable pour le ROR de s'appuyer également sur le JDV InteropSanté ? 
@nriss penses tu que la valeur "unité d'activité" de [fr-organization-type](https://simplifier.net/packages/hl7.fhir.fr.core/1.1.0/files/783673) peut se rapprocher de la notion "unité élémentaire" ?

2024-01-26 13:39 UTC, nriss commented on input/pagecontent/specifications_techniques_12.md
> +            "system": "http://interopsante.org/fhir/CodeSystem/fr-v2-3307",
Dommage qu'il y ait doublon entre les deux JDV !

Je ne sais pas à quoi correspond unité d'activité et unité élémentaire malheureusement

Peux-tu mettre une issue sur le GH de FrCore ?

2024-01-26 16:02 UTC, paulineheurtebise commented on input/pagecontent/specifications_techniques_12.md
> +            "system": "http://interopsante.org/fhir/CodeSystem/fr-v2-3307",
Issue FrCore : [#120](https://github.com/Interop-Sante/hl7.fhir.fr.core/issues/120)

2024-01-31 09:35 UTC, sly-kereval commented
Concernant le scénario d'ajout d'une Location à un HealthcareService, un scénario existe déjà dans le cas d'usage Création et Mise à jour du lieu de réalisation de l’offre : [scénario 1](https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/main/specifications_techniques_10.html#sc%C3%A9nario-1-ajout-dun-lieu-de-r%C3%A9alisation-de-loffre-draft). 

Nous avons donc référencé ce scénario sur la page du cas d'usage de mise à jour de l'offre (comme pour le scénario 9), voici la preview : https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/203-ajout-cas-usage-saisie-offre/specifications_techniques_13.html#scénario-11-ajout-dun-lieu-de-réalisation-de-loffre

Est-ce que cela vous convient @sdemeyANS, @jcserafini, @PhilippeC-ANS ?

2024-02-06 15:24 UTC, sdemeyANS commented
@sly-kereval et @paulineheurtebise suite à un échange avec @nriss sur https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/pull/265 on peut pour les nouvelles pages de specs donner un nom plus explicite exemple https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/pull/265/files#diff-48fb7e968ac7234e8b504e07b3d93dd7b408c952f22ff8a072f372c949dfddf4

2024-02-06 15:36 UTC, sdemeyANS commented
@sly-kereval et @paulineheurtebise 
<img width="625" alt="image" src="https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/assets/117643165/cdd58e2b-0302-4d2c-9e7d-dfeece2ca298">

le premier tableau peut être supprimé et dans le 2eme les requêtes doivent être dans des balises "code" pour être homogène avec le reste de l'IG
exemple 
https://interop.esante.gouv.fr/ig/fhir/ror/specifications_techniques_1.html

2024-02-07 08:45 UTC, sly-kereval commented
@sdemeyANS 
> le premier tableau peut être supprimé 

C'est déjà fait dans le main

> et dans le 2eme les requêtes doivent être dans des balises "code" pour être homogène avec le reste de l'IG exemple https://interop.esante.gouv.fr/ig/fhir/ror/specifications_techniques_1.html

C'est traité

2024-02-07 08:45 UTC, sly-kereval commented
> @sly-kereval et @paulineheurtebise suite à un échange avec @nriss sur #265 on peut pour les nouvelles pages de specs donner un nom plus explicite exemple https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/pull/265/files#diff-48fb7e968ac7234e8b504e07b3d93dd7b408c952f22ff8a072f372c949dfddf4

@sdemeyANS c'est traité

2024-02-08 13:14 UTC, paulineheurtebise commented on input/pagecontent/specifications_techniques_12.md
> +			"valueBoolean": true
@PhilippeC-ANS est ce que c'est ok pour toi ? si oui je te laisse résoudre la conversation. 
Sinon n'hésites pas si tu as des questions ou remarques.

2024-02-08 13:14 UTC, paulineheurtebise commented on input/pagecontent/specifications_techniques_12.md
> +			"valueDateTime": "2023-12"
@PhilippeC-ANS est ce que c'est ok pour toi ? si oui je te laisse résoudre la conversation. 
Sinon n'hésites pas si tu as des questions ou remarques.

2024-02-08 13:14 UTC, paulineheurtebise commented on input/pagecontent/specifications_techniques_12.md
> +			"valueDateTime": "2023-12"
@PhilippeC-ANS est ce que c'est ok pour toi ? si oui je te laisse résoudre la conversation. 
Sinon n'hésites pas si tu as des questions ou remarques.

2024-02-08 13:14 UTC, paulineheurtebise commented on input/pagecontent/specifications_techniques_12.md
>  #### Scénario 3 : Création de l'organisation interne d'un établissement
@PhilippeC-ANS est ce que c'est ok pour toi ? si oui je te laisse résoudre la conversation. 
Sinon n'hésites pas si tu as des questions ou remarques.

2024-02-08 13:14 UTC, paulineheurtebise commented on input/pagecontent/specifications_techniques_12.md
> +        "reference": "Organization/id"
@PhilippeC-ANS est ce que c'est ok pour toi ? si oui je te laisse résoudre la conversation. 
Sinon n'hésites pas si tu as des questions ou remarques.

2024-02-08 13:15 UTC, paulineheurtebise commented on input/pagecontent/specifications_techniques_12.md
> +            "system": "http://interopsante.org/fhir/CodeSystem/fr-v2-3307",
Les exemples ont été corrigés pour utiliser les éléments spécifiques au ROR

2024-02-21 11:17 UTC, sdemeyANS requested changes
un conflit à gérer pour préparer le futur merge ;)

2024-02-21 13:52 UTC, sdemeyANS commented on input/pagecontent/specifications_techniques_12.md
> +			"valueDateTime": "2023-12"
> Corrigé preview : https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/203-ajout-cas-usage-saisie-offre/specifications_techniques_12.html#sp%C3%A9cifique-serveur-sc%C3%A9nario-1-cr%C3%A9ation-de-lentit%C3%A9-juridique

attention le lien a changé @paulineheurtebise

2024-02-21 13:52 UTC, sdemeyANS commented on input/pagecontent/specifications_techniques_12.md
> +			"valueBoolean": true
attention le lien a changé @paulineheurtebise

2024-02-21 14:34 UTC, paulineheurtebise commented on input/pagecontent/specifications_techniques_12.md
> +			"valueDateTime": "2023-12"
Le lien de la preview modifié : [https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/203-ajout-cas-usage-saisie-offre/ig/saisie_offre.html#sp%C3%A9cifique-serveur-sc%C3%A9nario-2-cr%C3%A9ation-de-lentit%C3%A9-g%C3%A9ographique](https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/203-ajout-cas-usage-saisie-offre/ig/saisie_offre.html#sp%C3%A9cifique-serveur-sc%C3%A9nario-2-cr%C3%A9ation-de-lentit%C3%A9-g%C3%A9ographique)

2024-02-21 14:36 UTC, paulineheurtebise commented on input/pagecontent/specifications_techniques_12.md
> +			"valueDateTime": "2023-12"
Lien de la preview modifié : [https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/203-ajout-cas-usage-saisie-offre/ig/saisie_offre.html#sp%C3%A9cifique-serveur-sc%C3%A9nario-1-cr%C3%A9ation-de-lentit%C3%A9-juridique](https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/203-ajout-cas-usage-saisie-offre/ig/saisie_offre.html#sp%C3%A9cifique-serveur-sc%C3%A9nario-1-cr%C3%A9ation-de-lentit%C3%A9-juridique)

2024-02-21 14:37 UTC, paulineheurtebise commented
> un conflit à gérer pour préparer le futur merge ;)

Conflit résolu pour le futur merge

2024-03-13 16:01 UTC, sdemeyANS approved these changes

2024-03-13 16:35 UTC, merged