Scenario - Modif narratif avec exemples
ansforge/IG-fhir-repertoire-offre-ressources-sante pull request #267
Opened 2023-12-28 10:44 UTC by paulineheurtebise

Modification du narratif des scénarios "Recherche offre données capacitaires" : 

- #250
- #251 
- # 252

Modification du narratif des scénarios "Recherche offre sur critères principaux" :

- #248 
- #247 
- #246 
- #245 
- #243 
- #241 
- #240 
- #239 
- #238

2024-01-15 14:27 UTC, sly-kereval commented
La preview est disponible ici : https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/narratif-scenario-retour-platine

@jcserafini, @RomainCaraty, @sdemeyANS c'est ok pour vous ?

2024-01-24 15:47 UTC, sdemeyANS requested changes

2024-01-24 15:47 UTC, sdemeyANS commented on input/pagecontent/specifications_techniques_3.md
> +**Description du scénario :** Un consommateur cherche les offres ayant un type d'offre et une activité opérationnelle particulières, dans une commune faisant partie d'une zone d'intervention.
voir suggestion précédente

2024-01-30 15:16 UTC, sdemeyANS commented
> La preview est disponible ici : https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/narratif-scenario-retour-platine
> 
> @jcserafini, @RomainCaraty, @sdemeyANS c'est ok pour vous ?

@sly-kereval @mlr-kereval et @paulineheurtebise review faite de mon côté
@jcserafini et @RomainCaraty ok pour vous cette PR ?
cf preview
https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/narratif-scenario-retour-platine
et modifications : https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/pull/267/files

2024-01-30 15:46 UTC, sly-kereval commented on input/pagecontent/specifications_fonctionnelles.md
> +    - Un consommateur recherche les offres proposant une activité opérationnelle et un mode de prise en charge particuliers, sur une ville, ou un ensemble de villes (code commune).
Pris en compte

2024-01-30 15:46 UTC, sly-kereval commented on input/pagecontent/specifications_techniques_3.md
> +**Description du scénario :** Un consommateur cherche les offres ayant un type d'offre et une activité opérationnelle particulières, dans une commune faisant partie d'une zone d'intervention.
Pris en compte

2024-02-06 18:16 UTC, sdemeyANS approved these changes

2024-02-06 18:26 UTC, sdemeyANS commented
problème d'unité ? https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/issues/252

2024-02-06 18:27 UTC, sdemeyANS reviewed
peut être gérer le problème évoqué ici sur les unités? https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/issues/252 @paulineheurtebise et @sly-kereval ?

2024-02-08 12:52 UTC, paulineheurtebise commented
@RomainCaraty est ce que les modifications réalisées te conviennent ?

2024-02-16 10:33 UTC, paulineheurtebise commented
#244  Preview : [Ajout near scenario 6 ](https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/narratif-scenario-retour-platine/specifications_techniques_3.html#sc%C3%A9nario-6-recherche-%C3%A0-proximit%C3%A9-g%C3%A9ographique)

#241 Preview : [Ajout de l'age ](https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/narratif-scenario-retour-platine/specifications_techniques_3.html#sc%C3%A9nario-4-recherche-multicrit%C3%A8res-2---ou)

2024-02-16 14:11 UTC, paulineheurtebise commented
#313 - Preview : [Ajout scenario région source ](https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/narratif-scenario-retour-platine/specifications_techniques_1.html#sc%C3%A9nario-1ter-donn%C3%A9es-capacitaires-sur-une-r%C3%A9gion-source)

#316 - Preview :[ Ajout scenario 10 virgule ](https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/narratif-scenario-retour-platine/specifications_techniques_3.html#sc%C3%A9nario-10-recherche-sur-une-ville-2--code-commune)

2024-02-20 14:09 UTC, mlr-kereval commented
Typo corrigée sur #249
Requête validée #252 
Mise à jour de la requête + warning above #242

2024-02-20 14:10 UTC, mlr-kereval commented
@RomainCaraty peux-tu valider la PR ?

2024-02-21 08:23 UTC, RomainCaraty approved these changes

2024-02-21 08:51 UTC, sdemeyANS commented on input/pagecontent/specifications_techniques_4.md
> +&location.capacity-closing-type=https://mos.esante.gouv.fr/NOS/TRE_R333-TypeFermetureCapacite/TRE_R333-TypeFermetureCapacite|01&location.nb-capacity=gt0&_include=HealthcareService:location
typo @paulineheurtebise ?

2024-02-21 14:56 UTC, sdemeyANS commented on input/pagecontent/specifications_techniques_4.md
> +&location.capacity-closing-type=https://mos.esante.gouv.fr/NOS/TRE_R333-TypeFermetureCapacite/TRE_R333-TypeFermetureCapacite|01&location.nb-capacity=gt0&_include=HealthcareService:location
je corrige la typo :)

2024-02-21 15:10 UTC, merged