Sd add MS dans les profils ROR
ansforge/IG-fhir-repertoire-offre-ressources-sante pull request #269
Opened 2024-01-02 16:38 UTC by sdemeyANS

Changement voir issue #268
preview https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/sd-add-ms/artifacts.html

2024-01-24 16:43 UTC, nriss requested changes
merci :)
Un petit commentaire

2024-01-24 16:43 UTC, nriss commented on input/fsh/profiles/RORHealthcareService.fsh
> +* characteristic[receptionType].extension[ror-act-type] 0..0 MS
C'est étonnant de voir une cardinalité 0..0 avec un tag MS ?

2024-01-24 16:46 UTC, sdemeyANS commented on input/fsh/profiles/RORHealthcareService.fsh
> +* characteristic[receptionType].extension[ror-act-type] 0..0 MS
oui je devrais plutôt mettre * characteristic[receptionType] MS

2024-01-24 16:50 UTC, sdemeyANS commented on input/fsh/profiles/RORHealthcareService.fsh
> +* characteristic[receptionType].extension[ror-act-type] 0..0 MS
exact
surtout que dans preview cela barre le S 
<img width="584" alt="image" src="https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/assets/117643165/d2b7b64b-4524-4bfc-9789-be9391582ad4">

2024-01-24 16:53 UTC, nriss approved these changes

2024-01-24 16:55 UTC, sdemeyANS commented
> merci :) Un petit commentaire

bien vu :) merci :)

2024-01-29 13:25 UTC, LudivineLacour requested changes
Cela paraît logique a priori mais il manque le MS sur les id de chaque ressource. A mon sens cela pourrait créer de la confusion si le MS n'apparaît pas sur ces éléments.

2024-01-29 14:33 UTC, LudivineLacour commented
Relecture de PractitionerRole OK

2024-01-29 15:46 UTC, sdemeyANS commented
> Cela paraît logique a priori mais il manque le MS sur les id de chaque ressource. A mon sens cela pourrait créer de la confusion si le MS n'apparaît pas sur ces éléments.

A mon sens MS n'a pas sa place sur l'id. C'est un id logique ('technique') qui n'a pas de valeur métier et n'est pas profilé. On hérite directement du standard FHIR

2024-01-29 15:53 UTC, nriss commented
> > Cela paraît logique a priori mais il manque le MS sur les id de chaque ressource. A mon sens cela pourrait créer de la confusion si le MS n'apparaît pas sur ces éléments.
> 
> A mon sens MS n'a pas sa place sur l'id. C'est un id logique ('technique') qui n'a pas de valeur métier et n'est pas profilé. On hérite directement du standard FHIR

Après discussion avec Sylvain, je m'aligne à son avis! Effectivement, il est préférable de ne pas rentrer trop dans la technique FHIR qui est présente dans la doc officielle : l'usage de l'id est clairement explicitée dans la documentation et n'est pas propre au ROR

2024-02-02 09:00 UTC, LudivineLacour commented
Concernant l'usage des must support, il me semble qu'on s'était dit qu'on ne les mettaient pas uniquement sur les attributs propres au ROR mais aussi sur les éléments natifs hérités sinon cela n'a aucun intérêt. L'objectif est justement pour que l'on puisse visualiser facilement l'exhaustivité des attributs FHIR qui sont implémentés dans l'API du ROR National, y compris ceux hérités. 

Est-ce cette logique qui a été réalisée sur les MS ?

2024-02-02 09:06 UTC, sdemeyANS commented
> @sdemeyANS Concernant l'usage des must support, il me semble qu'on s'était dit qu'on ne les mettaient pas uniquement sur les attributs propres au ROR mais aussi sur les éléments natifs hérités sinon cela n'a aucun intérêt. L'objectif est justement pour que l'on puisse visualiser facilement l'exhaustivité des attributs FHIR qui sont implémentés dans l'API du ROR National, y compris ceux hérités.
> 
> Est-ce cette logique qui a été réalisée sur les MS ?

Hello. Normalement tout ce qui est mappé oui.
Quand c'est mappé on ajoute/précise dans la description le contexte d'usage dans le ROR même si on ne change pas la cardinalité.
Ensuite ce qui est natif est de facto de cardinalité 1 minimale est à supporter

2024-02-02 09:44 UTC, LudivineLacour commented
Justement je ne comprends pas pourquoi ne pas mettre le MS sur l'id car il est natif mais en cardinalité 0..1 sur les ressources. Uniquement parce que c'est un champ technique ? Je trouve ça un peu étrange et risqué en terme de bonne compréhension de l'IG par les éditeurs

2024-02-02 10:01 UTC, sdemeyANS commented
> Justement je ne comprends pas pourquoi ne pas mettre le MS sur l'id car il est natif mais en cardinalité 0..1 sur les ressources. Uniquement parce que c'est un champ technique ? Je trouve ça un peu étrange et risqué en terme de bonne compréhension de l'IG par les éditeurs

Parce que là c'est le standard FHIR. Au delà de l'IG les éditeurs, pour faire du FHIR, doivent regarder la documentation FHIR. 
https://interop.esante.gouv.fr/ig/documentation/demarrer_sur_fhir.html

2024-02-06 14:42 UTC, sdemeyANS commented
> > Justement je ne comprends pas pourquoi ne pas mettre le MS sur l'id car il est natif mais en cardinalité 0..1 sur les ressources. Uniquement parce que c'est un champ technique ? Je trouve ça un peu étrange et risqué en terme de bonne compréhension de l'IG par les éditeurs
> 
> Parce que là c'est le standard FHIR. Au delà de l'IG les éditeurs, pour faire du FHIR, doivent regarder la documentation FHIR. https://interop.esante.gouv.fr/ig/documentation/demarrer_sur_fhir.html

du coup @LudivineLacour ok pour la PR?

2024-02-07 10:44 UTC, jcserafini approved these changes
pas d'avis car pas d'impact dev

2024-02-07 13:51 UTC, LudivineLacour approved these changes
OK pour moi

2024-02-07 14:25 UTC, merged