Correction RC ror-location-equipment-limit
ansforge/IG-fhir-repertoire-offre-ressources-sante pull request #270
Opened 2024-01-03 11:21 UTC by sly-kereval

- Suppression de l'extension ror-location-equipment-limit dans le profil Location (car déplacée dans l'extension ROR-location-equipment)
- Mise à jour du mapping (à partir du fichier de la branche 229-incoherence-format-adresse-streetnametype pour anticiper les conflits)

2024-01-09 10:30 UTC, sdemeyANS requested changes
voir retour dev https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/issues/279
et gestion de conflit sur le xls de mapping

2024-01-10 16:46 UTC, paulineheurtebise commented
Maj de l'extension LocationEquipmentLimit pour corriger la syntaxe suite à l'issue #279.

2024-01-10 17:07 UTC, nriss approved these changes
Ok pour moi! Je n'ai pas vu le contenu du excel

2024-01-11 08:46 UTC, sdemeyANS approved these changes

2024-01-11 09:35 UTC, sdemeyANS commented
@sly-kereval je te laisse merge ?
merci

2024-01-11 09:36 UTC, merged