Modification requêtes union (_filter)
ansforge/IG-fhir-repertoire-offre-ressources-sante pull request #277
Opened 2024-01-09 08:34 UTC by sly-kereval

Modification des exemples requêtes qui recherchent une union de résultats avec la syntaxe implémentée (_filter au lieu de virgule) : 
- Consultation des données capacitaires : Scénario 1bis et 5
- Recherche d'offre sur critères principaux : Scénarios 2, 9 et 12
- Consultation des données capacitaires : Scénario 3 --> Déjà modifié dans la branche narratif-scenario-retour-platine-2

2024-01-09 08:48 UTC, sdemeyANS commented
Bonjour :)
C'est pour la version 0.2.0 ou pour la 0.2.1 qui embarquera les issues de Romain ?

2024-01-10 13:59 UTC, sdemeyANS requested changes
si c'est ce qui est implémenté il faut enlever draft aux scenarios qui le sont ?

2024-01-19 10:32 UTC, sly-kereval commented
> _filter a ajouté dans le narratif car présent uniquement dans les exemples.

_filter a été ajouté dans [les tableaux de critères de recherche](https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/275-recherche-union-filter/search_param.html) pour chaque ressources, c'est ok @jcserafini ?

2024-01-19 10:36 UTC, sly-kereval commented
> si c'est ce qui est implémenté il faut enlever draft aux scenarios qui le sont ?

Les scénarios concernés qui sont en draft sont les suivants : 
- Consultation des données capacitaires : Scénario 1bis
- Recherche d'offre sur critères principaux : Scénario 12

Est-ce qu'on enlève la mention "draft" ?

2024-01-22 13:23 UTC, sdemeyANS commented
> > si c'est ce qui est implémenté il faut enlever draft aux scenarios qui le sont ?
> 
> Les scénarios concernés qui sont en draft sont les suivants :
> 
> * Consultation des données capacitaires : Scénario 1bis
> * Recherche d'offre sur critères principaux : Scénario 12
> 
> Est-ce qu'on enlève la mention "draft" ?

@jcserafini ok pour toi?

2024-01-30 15:30 UTC, sdemeyANS commented
> > > si c'est ce qui est implémenté il faut enlever draft aux scenarios qui le sont ?
> > 
> > 
> > Les scénarios concernés qui sont en draft sont les suivants :
> > 
> > * Consultation des données capacitaires : Scénario 1bis
> > * Recherche d'offre sur critères principaux : Scénario 12
> > 
> > Est-ce qu'on enlève la mention "draft" ?
> 
> @jcserafini ok pour toi?

@jcserafini ok pour toi?

2024-02-13 14:50 UTC, jcserafini commented
Consultation des données capacitaires : Scénario 1bis
-> KO . Les dévs ont pas réussi a embarquer tous les critères en multi on a du prioriser. Ce scénar devrait être OK en 3.2

Recherche d'offre sur critères principaux : Scénario 12
-> KO : non planifié

le filter -> OK

2024-02-13 14:50 UTC, jcserafini requested changes
Consultation des données capacitaires : Scénario 1bis
-> KO . Les dévs ont pas réussi a embarquer tous les critères en multi on a du prioriser. Ce scénar devrait être OK en 3.2

Recherche d'offre sur critères principaux : Scénario 12
-> KO : non planifié

le filter -> OK

2024-02-14 13:07 UTC, paulineheurtebise commented
Atelier 14/02 : tag draft sur le scenario 12

2024-02-14 13:12 UTC, paulineheurtebise commented
Scénario déjà en draft : [https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/275-recherche-union-filter/specifications_techniques_3.html](https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/275-recherche-union-filter/specifications_techniques_3.html)

2024-02-16 09:37 UTC, paulineheurtebise commented
@sdemeyANS et @jcserafini 
ok pour vous ?

2024-02-16 10:23 UTC, sdemeyANS approved these changes

2024-02-16 10:25 UTC, sdemeyANS commented
> @sdemeyANS et @jcserafini ok pour vous ?

un conflit à gérer ;)

2024-02-16 15:49 UTC, jcserafini commented
@paulineheurtebise Pour répondre à ta question il faut enlever le OU

2024-02-16 15:49 UTC, jcserafini approved these changes

2024-02-16 16:02 UTC, paulineheurtebise commented
> @paulineheurtebise Pour répondre à ta question il faut enlever le OU

@jcserafini nous avions convenu il me semble mercredi que nous ne modifions pas le scénario mais nous le faisons apparaitre en draft. Tu confirmes ?

2024-02-26 13:37 UTC, jcserafini commented
@paulineheurtebise ça me convient !

2024-02-26 15:07 UTC, merged