Correction noms Organization
ansforge/IG-fhir-repertoire-offre-ressources-sante pull request #290
Opened 2024-01-19 08:46 UTC by sly-kereval

## Description des changements

* Mise en cohérence par rapport au modèle d'expo des cardinalités des éléments name et alias de la ressource Organization (#280)
* Amélioration de la description (short) des éléments name, alias et ror-organization-additional-name de la ressource Organization (#281)

## Preview

https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/280-281-correction-noms-orga/StructureDefinition-ror-organization.html

## Impact API ROR

Cardinalités et description à modifier

2024-01-22 12:50 UTC, sdemeyANS commented
@LudivineLacour est-ce que cela répond bien  à tes demandes ?
@jcserafini est-ce qu'il y a un impact dev avec les changements de cardinalité?

2024-01-23 10:14 UTC, sdemeyANS approved these changes
OK. Voir si ok pour @LudivineLacour et voir l'impact côté dev pour @jcserafini

2024-01-24 14:23 UTC, LudivineLacour approved these changes
C'est OK pour moi

2024-01-24 14:29 UTC, LudivineLacour requested changes
Faut-il impacter la modification de la cardinalité dans la page de l'extension additional-name qui est toujours à 0...* ? 

![image](https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/assets/25037491/69419687-25d0-4b0a-b5b9-a5c6cc60268f)


https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/280-281-correction-noms-orga/StructureDefinition-ror-organization-additional-name.html

2024-01-24 14:43 UTC, sly-kereval commented
> Faut-il impacter la modification de la cardinalité dans la page de l'extension additional-name qui est toujours à 0...* ?
> 
> ![image](https://private-user-images.githubusercontent.com/25037491/299346456-69419687-25d0-4b0a-b5b9-a5c6cc60268f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxMDY5ODYsIm5iZiI6MTcwNjEwNjY4NiwicGF0aCI6Ii8yNTAzNzQ5MS8yOTkzNDY0NTYtNjk0MTk2ODctMjVkMC00YjBhLWI1YjktYTVjNmNjNjAyNjhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDE0MzEyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxM2ZhY2Q3MTEyZjhmNGM1ZTIyMDkwMzY5ZWMyOTkyNjk0ZTMxMzg5NTEyODM0ZmQ2YmJjZjc0MjkwNDc3NmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s6z9qc2vW3GeITkMjA-7ONm2AaRqhVIjp-kp2--vuOo)
> 
> https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/280-281-correction-noms-orga/StructureDefinition-ror-organization-additional-name.html

@LudivineLacour non ce n'est pas nécessaire, il s'agit de la structure générale des extensions (voir http://hl7.org/fhir/R4/extensibility.html#extension)

2024-01-30 15:26 UTC, sdemeyANS commented
> > Faut-il impacter la modification de la cardinalité dans la page de l'extension additional-name qui est toujours à 0...* ?
> > ![image](https://private-user-images.githubusercontent.com/25037491/299346456-69419687-25d0-4b0a-b5b9-a5c6cc60268f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxMDY5ODYsIm5iZiI6MTcwNjEwNjY4NiwicGF0aCI6Ii8yNTAzNzQ5MS8yOTkzNDY0NTYtNjk0MTk2ODctMjVkMC00YjBhLWI1YjktYTVjNmNjNjAyNjhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDE0MzEyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxM2ZhY2Q3MTEyZjhmNGM1ZTIyMDkwMzY5ZWMyOTkyNjk0ZTMxMzg5NTEyODM0ZmQ2YmJjZjc0MjkwNDc3NmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s6z9qc2vW3GeITkMjA-7ONm2AaRqhVIjp-kp2--vuOo)
> > https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/280-281-correction-noms-orga/StructureDefinition-ror-organization-additional-name.html
> 
> @LudivineLacour non ce n'est pas nécessaire, il s'agit de la structure générale des extensions (voir http://hl7.org/fhir/R4/extensibility.html#extension)

@LudivineLacour si la réponse de Sarah te convient peux-tu approuver la PR stp ?

2024-01-30 15:41 UTC, sdemeyANS commented
> @LudivineLacour est-ce que cela répond bien à tes demandes ? @jcserafini est-ce qu'il y a un impact dev avec les changements de cardinalité?

@jcserafini est-ce qu'il y a un impact dev avec les changements de cardinalité?

2024-02-02 09:04 UTC, LudivineLacour approved these changes
La réponse de Sarah me convient

2024-02-07 10:34 UTC, jcserafini requested changes
cf commentaire sur https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/issues/280
Je pense qu'il faut éviter les cardinalités en 1..1 pour le moment

2024-02-14 09:15 UTC, sdemeyANS commented
> cf commentaire sur #280 Je pense qu'il faut éviter les cardinalités en 1..1 pour le moment

proposition de changement réalisé pour prendre en compte la demande @jcserafini et @LudivineLacour

2024-02-16 09:38 UTC, sly-kereval commented
Cardinalité de Organization.name passée à 0..1 comme demandé et indication ajoutée pour préciser que c'est provisoire

Preview : https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/280-281-correction-noms-orga/StructureDefinition-ror-organization.html

@sdemeyANS, @jcserafini, @LudivineLacour ok pour vous ?

2024-02-16 10:28 UTC, sdemeyANS commented
> Cardinalité de Organization.name passée à 0..1 comme demandé et indication ajoutée pour préciser que c'est provisoire
> 
> Preview : https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/280-281-correction-noms-orga/StructureDefinition-ror-organization.html
> 
> @sdemeyANS, @jcserafini, @LudivineLacour ok pour vous ?

@sly-kereval un conflit à gérer pour le merge ;) merci

2024-02-16 15:50 UTC, jcserafini approved these changes

2024-02-16 16:17 UTC, merged