Remplacement RORLocationStatus par operationalStatus
ansforge/IG-fhir-repertoire-offre-ressources-sante pull request #310
Opened 2024-02-08 13:39 UTC by sly-kereval

## Description des changements

Déplacement de l'attribut LieuRealisationOffre/statut de l'extension RORLocationStatus vers l'élément natif operationalStatus

## Preview

https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/260-location-status pour prévisualiser l'IG 

## Impact API ROR

Impact dev @jcserafini

2024-02-09 10:32 UTC, sdemeyANS requested changes
est-ce qu'il n'y a pas aussi un changement à faire dans le xls de mapping et dans https://interop.esante.gouv.fr/ig/fhir/ror/search_param.html?

2024-02-09 14:27 UTC, sly-kereval commented
> est-ce qu'il n'y a pas aussi un changement à faire dans le xls de mapping et dans https://interop.esante.gouv.fr/ig/fhir/ror/search_param.html?

Le xls de mapping a été mis à jour et le SP ajouté dans le tableau (il n'y était pas mais il était dans le CS)

2024-02-09 14:50 UTC, sdemeyANS commented
> > est-ce qu'il n'y a pas aussi un changement à faire dans le xls de mapping et dans https://interop.esante.gouv.fr/ig/fhir/ror/search_param.html?
> 
> Le xls de mapping a été mis à jour et le SP ajouté dans le tableau (il n'y était pas mais il était dans le CS)

oui je l'avais vu dans le CS :)

2024-02-09 14:52 UTC, sdemeyANS commented
> ## Description des changements
> Déplacement de l'attribut LieuRealisationOffre/statut de l'extension RORLocationStatus vers l'élément natif operationalStatus
> 
> ## Preview
> https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/260-location-status pour prévisualiser l'IG
> 
> ## Impact API ROR
> Impact dev @jcserafini

@jcserafini est ce que l'on peut le mettre dès à présent (prochaine version) dans l'IG ou il faudra le mettre dans la version ballot?

2024-02-09 14:55 UTC, sdemeyANS approved these changes
merci :)

2024-02-10 12:06 UTC, nriss approved these changes
Ok! Quel plaisir ce type de PR!

2024-02-10 12:06 UTC, nriss commented on input/pagecontent/search_param.md
> + <tr style='mso-yfti-irow:25'>
Ça doit être difficile à maintenir ces tableaux

2024-02-21 08:20 UTC, sdemeyANS commented
@jcserafini et @Mathieu-Rousseau pour qu'elle version du ROR cette modification peut être prise en compte ?

2024-04-11 12:51 UTC, sdemeyANS commented
@Mathieu-Rousseau pour rappel :) l'issue concernée https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/issues/260

2024-04-11 13:03 UTC, sdemeyANS commented
A noter que vu que cette PR commence à dater, beaucoup de conflits complexes à gérer maintenant

2024-05-03 12:15 UTC, sdemeyANS commented
> A noter que vu que cette PR commence à dater, beaucoup de conflits complexes à gérer maintenant

Le principe de la modif peut être validé pour être pris en compte dans l'implémentation du ROR, mais pour éviter toute erreur lors de la résolution de conflit je vais refaire une branche plus récente et une autre PR qui intégrera les modifications proposées

2024-05-03 14:43 UTC, sdemeyANS commented
Je ferme cette PR pour reprendre les travaux ici https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/pull/352

2024-05-03 14:43 UTC, closed without merging