Amelioration mapping
ansforge/IG-fhir-repertoire-offre-ressources-sante pull request #324
Opened 2024-03-01 14:07 UTC by mlr-kereval

## Description des changements

Création mapping manuel sur toutes les ressources du modèle d'exposition ROR v3 : 
- Structure definition
- Diagramme

## Preview

https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/amelioration-mapping/mapping.html

## Impact API ROR

Aucun à valider

2024-03-01 16:02 UTC, sdemeyANS commented
Bonjour, plusieurs erreurs sushi remontées dans le workflow
https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/actions/runs/8112637615/job/22175842795?pr=324

2024-03-04 07:34 UTC, sly-kereval commented
> Bonjour, plusieurs erreurs sushi remontées dans le workflow https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/actions/runs/8112637615/job/22175842795?pr=324

C'est corrigé :)

2024-03-04 10:50 UTC, nriss commented on input/fsh/extensions/RORHealthcareServiceContactTelecom.fsh
> +* extension[RORTelecomConfidentialityLevel] -> "niveauConfidentialite : JDV-J222-NiveauConfidentialite-ROR"
Faut-il mettre le binding associé ici ?

2024-03-06 09:43 UTC, sdemeyANS reviewed
pourquoi ne pas aussi exploiter comment pour le mapping ? on pourrait tester de mettre les profil d'accès par exemple.
![image](https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/assets/117643165/3211f57b-76e7-4060-969c-dc0a97cc2ce9)

=> 
<img width="686" alt="image" src="https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/assets/117643165/4849e315-e2a3-4e22-a862-e119176c768c">

2024-03-08 16:04 UTC, sdemeyANS commented on input/fsh/extensions/RORHealthcareServicePatientType.fsh
> +* extension[supportedPatientInfo] -> "publicPrisEnCharge : JDV-J29-PublicPrisEnCharge-ROR"
@sly-kereval on te laisse voir ce point comme vu lors de l'atelier de ce jour

2024-03-08 16:04 UTC, nriss commented on input/fsh/profiles/ROROrganization.fsh
> +
A supprimer ?

2024-03-08 16:06 UTC, sdemeyANS commented on input/fsh/extensions/RORHealthcareServiceContactTelecom.fsh
> +* extension[RORTelecomConfidentialityLevel] -> "niveauConfidentialite : JDV-J222-NiveauConfidentialite-ROR"
A enlever pour l'automatisation cf issue #327

2024-03-08 16:06 UTC, nriss requested changes
Ok sous réserve de deux corrections :
- les attributs FHIR sont mappés au niveau des types primitifs (aller jusqu'au .valueString par ex.)
- le binding des JDV est supprimé

2024-03-11 17:24 UTC, sdemeyANS approved these changes
sous réserve réponse à mes commentaires et réponses à ceux de @nriss

2024-03-11 17:24 UTC, sdemeyANS commented on input/fsh/profiles/ROROrganization.fsh
> +
ligne vide ?

2024-03-11 17:24 UTC, sdemeyANS commented on input/pagecontent/mapping.md
>  <p style="background-color: #ffcccc; border:1px solid grey; padding: 5px; max-width: 790px;">
il faudrait l'intégrer ailleurs le lien vers le xls peut être dans Mapping global ?

2024-03-11 17:24 UTC, sdemeyANS commented on input/pagecontent/mapping.md
>  A noter que Task, Measure et MeasureReport ne font pas partie du mapping, car cela ne fait pas partie du modèle d'exposition du ROR
Je mettrai bien aussi une 2eme remarque pour signifier que cette page est encore en mode "draft" pour siginifier que sa maturité est encore 'jeune ' :)

2024-03-11 17:40 UTC, nriss approved these changes

2024-03-12 09:13 UTC, sly-kereval commented
Modifications : 
- Binding des JDV supprimé dans le mapping de la SD
- Lien vers le mapping excel déplacé sous le schéma global de mapping
- Ajout d'un tag draft sur la page mapping 
- Harmonisation du niveau du mapping (type primitif) : concernant ce point nous avons identifié des cas particuliers (notamment pour pouvoir générer les schémas tels qu'ils sont dans cette branche), voir ci-dessous : 

Propositions à valider (@sdemeyANS, @nriss) concernant le niveau du mapping (type primitif sauf exceptions ci-dessous) : 
- Pour certains éléments complexes dont le type n’est pas primitif, il semble nécessaire de conserver le mapping quand celui-ci correspond à une classe ou un type de données du ME.
  - Par exemple l’extension ror-territorial-division représente le type de données DivisionTerritoriale, 2 attributs du ME sont de ce type : OffreOperationnelle.zoneIntervention et EG.territoireSante. Dans ce cas, dans les SD des ressources concernées (HealthcareService et Organization) il semble intéressant de garder l’information des attributs du ME qui sont mappés sur cette extension. Autres exemples : availableTime (horaire), meta (metadonnees), position (coordonneeGeographique), telecom (boiteLettreMSS, telecommunication) …
- Pour les extensions héritées, le mapping est laissé dans la SD de la ressource.
  - Par exemple address.line, PractitionerRole. contracted
- Dans le cas de plusieurs classes mappées sur une seule ressource (par exemple Organization : EJ, EG, OI) :
  - Certaines extensions sont utilisées seulement pour une classe (par exemple ror-organization-financial-help-type seulement pour EG). Dans ce cas on a besoin de mettre le mapping dans la SD en plus de l’extension car sinon on a pas l’info.
  - Certaines extensions sont mappées sur des attributs dont les noms sont différents (par exemple l’extension ror-organization-additional-name :  EJ.complementRaisonSociale/ EG.complementDenominationEG). Idem, dans ce cas on a besoin de mettre le mapping dans la SD en plus de l’extension car sinon on a pas l’info, et dans l’extension on met les 2 attributs.

2024-03-12 09:14 UTC, sly-kereval commented on input/fsh/extensions/RORHealthcareServiceContactTelecom.fsh
> +* extension[RORTelecomConfidentialityLevel] -> "niveauConfidentialite : JDV-J222-NiveauConfidentialite-ROR"
Les bindings ont été supprimées

2024-03-12 09:14 UTC, sly-kereval commented on input/fsh/profiles/ROROrganization.fsh
> +
Ligne vide supprimée

2024-03-12 09:15 UTC, sly-kereval commented on input/pagecontent/mapping.md
>  A noter que Task, Measure et MeasureReport ne font pas partie du mapping, car cela ne fait pas partie du modèle d'exposition du ROR
Tag draft ajouté

2024-03-12 11:15 UTC, sdemeyANS commented on input/fsh/extensions/RORHealthcareServicePatientType.fsh
> +* extension[supportedPatientInfo] -> "publicPrisEnCharge : JDV-J29-PublicPrisEnCharge-ROR"
@ok pour toi @nriss ?
Si oui on peut merge cette 1st iteration et voir la suite dans #327 @sly-kereval je pense

2024-03-12 15:32 UTC, sdemeyANS commented
les liens dans la colonne parent renvoi vers R5 et pour FRorganization le lien est KO @sly-kereval 
https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/amelioration-mapping/ig/index.html#ressources-profil%C3%A9es

2024-03-12 15:37 UTC, sdemeyANS commented
> les liens dans la colonne parent renvoi vers R5 et pour FRorganization le lien est KO @sly-kereval https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/amelioration-mapping/ig/index.html#ressources-profil%C3%A9es

si trop long à résoudre aujourd'hui je propose de commenter ce sous chapitre dans index.md et voir dans la prochaine itération sur mapping @sly-kereval et @nriss ?

2024-03-12 15:49 UTC, mlr-kereval commented
> > les liens dans la colonne parent renvoi vers R5 et pour FRorganization le lien est KO @sly-kereval https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/amelioration-mapping/ig/index.html#ressources-profil%C3%A9es
> 
> si trop long à résoudre aujourd'hui je propose de commenter ce sous chapitre dans index.md et voir dans la prochaine itération sur mapping @sly-kereval et @nriss ?

@sdemeyANS nous ne pouvons pas apporter de correction aujourd'hui

2024-03-12 15:55 UTC, sdemeyANS commented
> > > les liens dans la colonne parent renvoi vers R5 et pour FRorganization le lien est KO @sly-kereval https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/amelioration-mapping/ig/index.html#ressources-profil%C3%A9es
> > 
> > 
> > si trop long à résoudre aujourd'hui je propose de commenter ce sous chapitre dans index.md et voir dans la prochaine itération sur mapping @sly-kereval et @nriss ?
> 
> @sdemeyANS nous ne pouvons pas apporter de correction aujourd'hui

pas de souci. J'ai vu la même chose sur l'annuaire. On le traitera à part. du coup on comment cette partie je préfère pour pas embrouiller les consommateurs

2024-03-12 15:56 UTC, sdemeyANS commented on input/fsh/extensions/RORHealthcareServicePatientType.fsh
> +* extension[supportedPatientInfo] -> "publicPrisEnCharge : JDV-J29-PublicPrisEnCharge-ROR"
@nriss ok. On peut merge en l'état @sly-kereval merci :)

2024-03-12 16:05 UTC, sdemeyANS commented
> > > > les liens dans la colonne parent renvoi vers R5 et pour FRorganization le lien est KO @sly-kereval https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/amelioration-mapping/ig/index.html#ressources-profil%C3%A9es
> > > 
> > > 
> > > si trop long à résoudre aujourd'hui je propose de commenter ce sous chapitre dans index.md et voir dans la prochaine itération sur mapping @sly-kereval et @nriss ?
> > 
> > 
> > @sdemeyANS nous ne pouvons pas apporter de correction aujourd'hui
> 
> pas de souci. J'ai vu la même chose sur l'annuaire. On le traitera à part. du coup on comment cette partie je préfère pour pas embrouiller les consommateurs

c'est bon @nriss à enlever la colonne Parent https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/pull/332

2024-03-12 17:21 UTC, merged