#327 Automatisation mapping
ansforge/IG-fhir-repertoire-offre-ressources-sante pull request #342
Opened 2024-03-19 16:54 UTC by mlr-kereval

## Description des changements

Ajout des profils d'accès dans la partie "Mappings" (Excel mappingFHIR_ROR_ME3_2024_01_10.xlsx)
Mise à disposition des scripts de mapping pour générer le schéma global ainsi que les schémas par profils : [PR-19](https://github.com/ansforge/IG-workflows/pull/19)

## Preview

[https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/ig/[nom_de_la_branche] pour prévisualiser l'IG d'une branche](https://ansforge.github.io/IG-fhir-repertoire-offre-ressources-sante/327-automatisation-mapping/ig/artifacts.html)

## Impact API ROR

2024-03-25 08:08 UTC, nriss requested changes
Est-ce qu'il y a écrit qq part à quoi correspondent les profils ?

2024-03-25 08:08 UTC, nriss commented on input/fsh/extensions/RORAvailableTimeEffectiveOpeningClosingDate.fsh
> +* valuePeriod.start -> "debutDateEffective" "RORPractitionerRole : Profil 1,
<img width="1364" alt="image" src="https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/assets/48218773/359febad-e9e6-48ff-89f6-e4e4f5a49aea">

C'est difficile à lire
As-tu essayé avec des \n ?

2024-03-25 08:46 UTC, sdemeyANS commented
> Est-ce qu'il y a écrit qq part à quoi correspondent les profils ?


oui mais c'est hors IG. C'est la poilitique d'accès du ROR
<img width="487" alt="image" src="https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/assets/117643165/94883fb9-05ad-4b85-a54c-0ace49ceb37f">

2024-04-02 15:59 UTC, nriss approved these changes

2024-04-02 16:01 UTC, sdemeyANS approved these changes
on gèrera les \n pour les profils dans une autre PR

2024-04-02 16:01 UTC, merged