[RC]Ajout search params _content dans CS
ansforge/IG-fhir-repertoire-offre-ressources-sante pull request #44
Opened 2023-05-24 12:12 UTC by sly-kereval

2023-06-05 09:04 UTC, sdemeyANS requested changes

2023-06-05 09:04 UTC, sdemeyANS commented on input/fsh/instances/ror-consommateur.fsh
> +* rest.resource[=].searchParam[=].definition = "http://hl7.org/fhir/SearchParameter/Resource-content"
on doit pas spécifier R4?

2023-06-07 16:04 UTC, sdemeyANS commented
@sly-kereval dans les CS il ne faudra pas aussi préciser R4 pour les searchParam?

2023-06-08 08:25 UTC, sly-kereval commented on input/fsh/instances/ror-consommateur.fsh
> +* rest.resource[=].searchParam[=].definition = "http://hl7.org/fhir/SearchParameter/Resource-content"
En effet ça serait pertinent mais dans l'url canonique des search param (http://hl7.org/fhir/SearchParameter/[id]) j'ai l'impression qu'il n'est pas possible de préciser la version.

2023-06-12 07:41 UTC, nriss approved these changes
Ok pour moi

2023-06-12 07:41 UTC, nriss commented on input/fsh/instances/ror-consommateur.fsh
> +* rest.resource[=].searchParam[=].definition = "http://hl7.org/fhir/SearchParameter/Resource-content"
Oui l'url canonique ne précise pas la version

2023-06-13 08:26 UTC, sdemeyANS commented on input/fsh/instances/ror-consommateur.fsh
> +* rest.resource[=].searchParam[=].definition = "http://hl7.org/fhir/SearchParameter/Resource-content"
@nriss du coup pas gênant de laisser ces url dans le CS ?

2023-06-13 08:44 UTC, sdemeyANS commented on input/fsh/instances/ror-consommateur.fsh
> +* rest.resource[=].searchParam[=].definition = "http://hl7.org/fhir/SearchParameter/Resource-content"
ok on laisse comme ça alors

2023-06-16 10:33 UTC, merged