Livraison 17/02/23
ansforge/IG-fhir-repertoire-offre-ressources-sante pull request #6
Opened 2023-02-17 17:19 UTC by paulineheurtebise

Retravail des nomenclatures avec retours 2.4

2023-02-22 15:57 UTC, sdemeyANS requested changes

2023-02-22 15:57 UTC, sdemeyANS commented on input/fsh/profiles/RORPractitioner.fsh
> +* id 1..1
pourquoi id obligatoire ici?

2023-02-22 15:57 UTC, sdemeyANS commented on input/fsh/profiles/RORPractitioner.fsh
> +* id 1..1
à uniformiser sur l'ensemble des profils et expliquer/commenter la justification si elle existe

2023-02-22 15:57 UTC, sdemeyANS commented on input/fsh/profiles/RORPractitionerRole.fsh
> +* identifier 0..1
Pouvez-vous commenter/expliquer ce choix svp ?

2023-02-22 15:57 UTC, sdemeyANS commented on sushi-config.yaml
> +canonical: http://interop.esante.gouv.fr/fhir/ig/ror30
http://interop.esante.gouv.fr/fhir/ig/ror30 à remplacer par https://interop.esante.gouv.fr/ig/fhir/ror30

2023-02-22 15:57 UTC, sdemeyANS commented on sushi-config.yaml
>  title: ROR
name: ROR ME 3.0
title: "ROR ME 3.0"
description: Ressources de conformité basées sur le modèle d'exposition 3.0 du ROR

2023-02-23 09:35 UTC, TristanKEREVAL commented on input/fsh/aliases.fsh
> +Alias: $JDV_J185-typeFermeture-ROR = https://mos.esante.gouv.fr/NOS/JDV_J185-typeFermeture-ROR/FHIR/JDV-J185-typeFermeture-ROR/
@paulineheurtebise  est ce que tu as une idée ?

2023-02-23 10:05 UTC, TristanKEREVAL commented on input/fsh/instances/ror-sp-additional-bed-type.fsh
> +* expression = "Location.extension.where(url='http://interop.esante.gouv.fr/fhir/ig/ror30/StructureDefinition/ror-supported-capacity').extension(url='additionalBedType').valueCode"
Donc dans le yaml on vient changer :
canonical: http://interop.esante.gouv.fr/fhir/ig/ror30
par
canonical: https://interop.esante.gouv.fr/ig/fhir/ror30
 ?

2023-02-23 10:07 UTC, paulineheurtebise commented on input/fsh/aliases.fsh
> +Alias: $JDV_J185-typeFermeture-ROR = https://mos.esante.gouv.fr/NOS/JDV_J185-typeFermeture-ROR/FHIR/JDV-J185-typeFermeture-ROR/
J201 -> typeFermeture EJ/EG
J185 -> typeFermeture offre 
On a commenté dans le fichier des alias

2023-02-23 10:51 UTC, nriss commented on input/fsh/aliases.fsh
> +Alias: $JDV_J185-typeFermeture-ROR = https://mos.esante.gouv.fr/NOS/JDV_J185-typeFermeture-ROR/FHIR/JDV-J185-typeFermeture-ROR/
Top, vous n'avez pas encore push c'est ça ?
Attention il y a un slash à la fin de l'url du JDV J185

2023-02-23 10:52 UTC, nriss commented on input/fsh/instances/ror-sp-additional-bed-type.fsh
> +* expression = "Location.extension.where(url='http://interop.esante.gouv.fr/fhir/ig/ror30/StructureDefinition/ror-supported-capacity').extension(url='additionalBedType').valueCode"
C'est ça :)
Et dans les CapabilityStatement et SearchParam également, globalement partout où l'url est écrite en dure! (le mieux c'est de faire un search sur l'ensemble des fichiers)

2023-02-23 11:12 UTC, paulineheurtebise commented on input/fsh/aliases.fsh
> +Alias: $JDV_J185-typeFermeture-ROR = https://mos.esante.gouv.fr/NOS/JDV_J185-typeFermeture-ROR/FHIR/JDV-J185-typeFermeture-ROR/
Je viens de le push. 
Effectivement il restait 2 / c'est aussi corrigé

2023-02-23 11:15 UTC, paulineheurtebise commented on input/fsh/extensions/RORAvailableTimeEffectiveOpeningClosingDate.fsh
> +Description: "Extension créée dans le cadre du ROR "
Compléter, sera présent dans le prochain push

2023-02-23 11:16 UTC, paulineheurtebise commented on input/fsh/extensions/RORCareWithoutPatientApproval.fsh
> -Extension: RORCareWithoutPatientApproval
en doublon avec RORHealthcareServiceNoConsentHabilitation.

2023-02-23 11:18 UTC, paulineheurtebise commented on input/fsh/extensions/RORHealthcareServiceContact.fsh
> +Description: "Extension créée dans le cadre du ROR"
Compléter, sera disponible dans le prochain push

2023-02-23 11:20 UTC, paulineheurtebise commented on input/fsh/extensions/ROROrganizationPrice.fsh
>  * extension[surchargePriceName].extension[string].value[x] only string
Modifier, on a détailler les 2 attributs en otherAdditionalServiceName (eq à nomAutrePrestationSupp) et additionalServiceName (eq à nomPrestationSupp).

2023-02-23 11:21 UTC, paulineheurtebise commented on input/fsh/extensions/RORPractitionerRoleHomeVisit.fsh
> -Extension: RORPractitionerRoleHomeVisit
Attribut supprimé en 3.0 dans le modèle d'expo

2023-02-23 11:22 UTC, paulineheurtebise commented on input/fsh/extensions/RORUnitExerciseMode.fsh
> -Extension: RORUnitExerciseMode
Extension en doublon avec RORPractitionerRoleUnitExerciceMode

2023-02-23 11:24 UTC, paulineheurtebise commented on input/fsh/instances/ror-sp-location-commune-cog.fsh
> +* description = "Paramètre de recherche permettant d'indiquer s'il y a une zone poser sur le site concerné"
Non, on a mise à jour. c'est corrigé.

2023-02-23 13:13 UTC, TristanKEREVAL commented on input/fsh/extensions/ROROrganizationPeriod.fsh
> +Description: "Extension créée dans le cadre du ROR pour définir les période d'ouverture et de fermeture de l'organisation interne"
Problème corrigé, même process qu'en 2.4 avec la reprise des SD d'HL7. On repart sur une extension complexe et on appelle l'extension d'HL7 dans l'organization

2023-02-23 13:20 UTC, TristanKEREVAL commented on input/fsh/extensions/ROROrganizationTerritorial.fsh
>  * extension ^slicing.discriminator.type = #value
Modifié en 3.0, je laisse ouvert pour le faire e,n 2.4

2023-02-23 13:25 UTC, TristanKEREVAL commented on input/fsh/profiles/RORPractitionerRole.fsh
> +* identifier 0..1
Mise en correspondance avec le modèle d'expo pour l'attribut "identifiant situation opérationnelle"

2023-02-27 14:01 UTC, nriss requested changes

2023-02-27 14:01 UTC, nriss commented on input/fsh/profiles/RORPractitionerRole.fsh
> +* specialty ^slicing.discriminator.path = "coding.system"
Attention ça n'est pas super de faire un discriminant sur coding.system alors qu'on fixe des JDV : potentiellement, deux JDV peuvent contenir le même code issu du même system. Dans ce cas : on est plus discriminant.

Voyez-vous une solution ?

2023-02-27 14:01 UTC, sdemeyANS requested changes

2023-02-28 14:03 UTC, TristanKEREVAL commented on input/fsh/extensions/RORContactFunctionContact.fsh
> +* ^context.expression = "BackboneElement" //TODO question Tristan --> verif Backbone
On a mit backbone element car c'est une extension quoi oit être utilisée au sein d'une autre extension. Visiblement on ne peut pas mettre "extension" dans le context.expression

2023-02-28 14:05 UTC, TristanKEREVAL commented on input/fsh/extensions/RORLocationSupportedCapacity.fsh
>  * extension[capacitySourceType].value[x] only code
Les types de données étaient issu du mapping mais on peut revoir ça

2023-02-28 14:06 UTC, TristanKEREVAL commented on input/fsh/index.txt
>  RORAddressStatus                                Extension  extensions\RORAddressStatus.fsh
Je crois que c'est un fichier généré par GOFSH mais non on ne le tiens pas à jour

2023-02-28 14:24 UTC, TristanKEREVAL commented on input/fsh/profiles/RORHealthcareService.fsh
> +* notAvailable contains
Effectivement, j'avais pensé que les slices étaient des sous éléments de l’élément mère et donc que c'était faisable

2023-02-28 15:18 UTC, nriss commented on input/fsh/extensions/RORContactFunctionContact.fsh
> +* ^context.expression = "BackboneElement" //TODO question Tristan --> verif Backbone
Dans ce cas, pourquoi ne pas l'avoir mis au sein d'une extension complexe ?

2023-02-28 15:20 UTC, nriss commented on input/fsh/extensions/RORLocationSupportedCapacity.fsh
>  * extension[capacitySourceType].value[x] only code
C'est dans le MOS où il y a code et codeableconcept ?

Je suis plutôt d'optique de mettre CodeableConcept partout, mais c'est à discuter, peut-être que la spec FHIR dit qqc à ce sujet sur le choix

2023-02-28 15:21 UTC, nriss commented on input/fsh/index.txt
>  RORAddressStatus                                Extension  extensions\RORAddressStatus.fsh
A supprimer si ça n'engendre pas d'erreurs

2023-02-28 15:21 UTC, TristanKEREVAL commented on input/fsh/extensions/RORLocationEquipment.fsh
> +* extension[equipmentType].value[x] from $JDV-J18-EquipementSpecifique-ROR (required)
Est ce qu'on applique le même fonctionnement sur le value[x] des extensions ?
Qqchose de ce style : * valueCodeableConcept from $JDV-J224-StatutLieu-ROR (required)
Au lieu de : 
* value[x] only CodeableConcept
* value[x] from $JDV-J224-StatutLieu-ROR(required)

On change pas mal la SD généré de cette façon non ? On ne limite plus le type de value à CodeableConcept

2023-02-28 15:27 UTC, nriss commented on input/fsh/extensions/RORLocationEquipment.fsh
> +* extension[equipmentType].value[x] from $JDV-J18-EquipementSpecifique-ROR (required)
Il faut laisser le only codeableconcept 
C’est juste pour la lisibilité à mon sens, je pense que la SD ne changera pas

2023-02-28 15:35 UTC, TristanKEREVAL commented on input/fsh/extensions/RORLocationEquipment.fsh
> +* extension[equipmentType].value[x] from $JDV-J18-EquipementSpecifique-ROR (required)
ça me génère une erreur si je met : 
* value[x] only CodeableConcept from $JDV-J41-TypeHoraire-ROR (required)

2023-02-28 16:29 UTC, nriss commented on input/fsh/extensions/RORLocationEquipment.fsh
> +* extension[equipmentType].value[x] from $JDV-J18-EquipementSpecifique-ROR (required)
value[x] only CodeableConcept
valueCodeableConcept from $JDV-J224-StatutLieu-ROR (required)

https://build.fhir.org/ig/HL7/fhir-shorthand/reference.html#defining-profiles

2023-03-01 08:56 UTC, TristanKEREVAL commented on input/fsh/aliases.fsh
> +Alias: $geolocation = http://hl7.org/fhir/StructureDefinition/geolocation
Ok ça me va

2023-03-01 09:17 UTC, TristanKEREVAL commented on input/fsh/extensions/RORContactFunctionContact.fsh
> +* ^context.expression = "BackboneElement" //TODO question Tristan --> verif Backbone
C'est à dire que ce fichier seul n'existerait plus mais on l'intégrerait au sein d'autres extensions qui sont déjà utilisés là où on en a besoin ?

2023-03-01 09:19 UTC, TristanKEREVAL commented on input/fsh/extensions/RORLocationEquipment.fsh
> +* extension[equipmentType].value[x] from $JDV-J18-EquipementSpecifique-ROR (required)
ok ça me va, du coup il faudra faire attention à bien appeler : valueCodeableConcept dans le cadre où on souhaiterait changer la cardinalité de la value au sein d'un profil appelant l'extension, c'est bien ça ?

2023-03-01 09:33 UTC, nriss commented on input/fsh/extensions/RORContactFunctionContact.fsh
> +* ^context.expression = "BackboneElement" //TODO question Tristan --> verif Backbone
Qu'est-ce qui t'a poussé à déclarer l'extension à part ?

2023-03-01 09:38 UTC, nriss commented on input/fsh/extensions/RORLocationEquipment.fsh
> +* extension[equipmentType].value[x] from $JDV-J18-EquipementSpecifique-ROR (required)
Je ne comprends pas pourquoi il faudrait changer la cardinalité de la value d'une extension au sein d'un profil
Selon moi, c'est une meilleure pratique de mettre une cardinalité sur les slices du champs extension du profil (ex : appliquer x fois obligatoirement une extension au profil patient)

2023-03-01 09:52 UTC, TristanKEREVAL commented on input/fsh/extensions/RORLocationSupportedCapacity.fsh
>  * extension[capacitySourceType].value[x] only code
Dans le modèle d'expo c'est noté de type Code, Pas de correspondance dans le MOS donc on peut partir sur CC partout

2023-03-01 09:55 UTC, nriss commented on input/fsh/extensions/RORLocationSupportedCapacity.fsh
>  * extension[capacitySourceType].value[x] only code
Super :)

2023-03-01 10:10 UTC, TristanKEREVAL commented on input/fsh/extensions/RORContactFunctionContact.fsh
> +* ^context.expression = "BackboneElement" //TODO question Tristan --> verif Backbone
Pas trop d'explication, On doit retrouver à la fois l'information dans une extension qui s'applique à HealthcareService (RORHealthcareServiceContact) et doit s'appliquer à Organization. Donc le plan serait de rajouter la slice directement sous RORHealthcareServiceContact et comme ça on peut juste laisser le context pour l'organization

2023-03-01 10:23 UTC, nriss commented on input/fsh/extensions/RORContactFunctionContact.fsh
> +* ^context.expression = "BackboneElement" //TODO question Tristan --> verif Backbone
Gardons ce point pour en discuter mardi :)

2023-03-01 12:41 UTC, TristanKEREVAL commented on input/fsh/profiles/ROROrganization.fsh
> +* identifier[idNatStruct].type = $JDV-J236-TypeIdentifiant-ROR#40 (exactly)
Pourquoi on ne peut pas mettre le JDV qui contient toutes les valeurs possibles ?

2023-03-01 13:22 UTC, TristanKEREVAL commented on input/fsh/profiles/RORPractitionerRole.fsh
> +* specialty ^slicing.discriminator.path = "coding.system"
On peut changer la fixed value sur les URL des TRE

2023-03-01 13:34 UTC, TristanKEREVAL commented on input/fsh/profiles/RORPractitionerRole.fsh
> +* specialty ^slicing.discriminator.path = "coding.system"
Mais là les system qu'on a mit ne peuvent pas se croiser, enfin de ce que je comprends, vu que ceux sont des JDV et que chaque slice appelle un JDV différent. à rediscuter mardi !

2023-03-01 13:44 UTC, TristanKEREVAL commented on input/fsh/extensions/RORTelecomUsage.fsh
> -* ^context.expression = "Practitioner.telecom"
Pour rendre l'extension réutilisable sur les autres ressources au lieu d'en avoir plusieurs

2023-03-01 14:17 UTC, nriss commented on input/fsh/profiles/ROROrganization.fsh
> +* identifier[idNatStruct].type = $JDV-J236-TypeIdentifiant-ROR#40 (exactly)
* identifier[idNatStruct].type = $JDV-J236-TypeIdentifiant-ROR#40

Quand on utilise une termino dans une instance de ressource, il faut utiliser l'URL du CodeSystem et non du ValueSet.
En écrivant $JDV-J236-TypeIdentifiant-ROR#40, tu dis : fixe le type avec l'url du JDV et avec le code 40.

2023-03-01 14:19 UTC, nriss commented on input/fsh/profiles/RORPractitionerRole.fsh
> +* specialty ^slicing.discriminator.path = "coding.system"
Deux JDV peuvent contenir le même code issu d'une TRE potentiellement, c'est pour ça que c'est pas une super pratique

2023-03-02 08:10 UTC, TristanKEREVAL commented on input/fsh/extensions/RORConfidentialityLevel.fsh
> +* value[x] 1..1
Pas d'explication particulière, je préfère mettre le value 1..1 même avec la règle de gestion mais est ce que c'est gênant/problématique si on le met ?

2023-03-02 08:48 UTC, nriss commented on input/fsh/extensions/RORConfidentialityLevel.fsh
> +* value[x] 1..1
A mon sens c'est pas nécessaire, dans la doc d'extensibility:
![image](https://user-images.githubusercontent.com/48218773/222377839-ee85f826-0d6b-4d85-8d53-d26757584bcd.png)
https://hl7.org/fhir/extensibility.html

C'est obligatoire d'avoir soit une value soit une extension, donc c'est déjà défini par la sec FHIR

2023-03-02 09:05 UTC, paulineheurtebise commented on input/fsh/extensions/ROROrganizationPeriod.fsh
> +Description: "Extension créée dans le cadre du ROR pour définir les période d'ouverture et de fermeture de l'organisation interne"
Corrigé dans le dernier commit

2023-03-02 09:10 UTC, paulineheurtebise commented on input/fsh/profiles/RORLocation.fsh
> +Description: "Profil créé dans le cadre du ROR pour décrire les moyens qui peuvent être mis en œuvre pour réaliser la prestation"
D'accord on a modifié en reprenant la définition de LieuRealisationOffre directement.

2023-03-02 09:13 UTC, paulineheurtebise commented on input/fsh/profiles/ROROrganization.fsh
> +* identifier 1..1
Corrigé à 1..*

2023-03-02 09:24 UTC, paulineheurtebise commented on input/fsh/profiles/RORPractitioner.fsh
> +* meta.tag 0..1
Corrigé

2023-03-02 09:25 UTC, paulineheurtebise commented on input/fsh/profiles/RORPractitioner.fsh
> +* id 1..1
Suppression de la contrainte

2023-03-02 09:29 UTC, paulineheurtebise commented on input/fsh/profiles/RORPractitionerRole.fsh
> +* meta.tag 0..1
Corrigé

2023-03-02 09:36 UTC, paulineheurtebise commented on input/fsh/extensions/RORConfidentialityLevel.fsh
> +* value[x] 1..1
Corrigé pour les extensions Telecom. En cours pour les autres.

2023-03-02 09:47 UTC, paulineheurtebise commented on input/fsh/extensions/RORContactTelecomConfidentialityLevel.fsh
>  Description: "Extension créée dans le cadre du ROR"
Corrigé

2023-03-02 09:48 UTC, paulineheurtebise commented on input/fsh/extensions/RORContactTelecomUsage.fsh
>  Description: "Extension créée dans le cadre du ROR"
Corrigé

2023-03-02 09:50 UTC, paulineheurtebise commented on input/fsh/instances/ror-sp-limit-value.fsh
>  * description = "Paramètre de recherche pour récupérer la valeur limite"
Corrigé.

2023-03-02 09:50 UTC, paulineheurtebise commented on input/fsh/profiles/ROROrganization.fsh
> +* id 1..1
Corrigé

2023-03-10 09:49 UTC, paulineheurtebise commented on input/fsh/profiles/ROROrganization.fsh
>  * type[organizationType] from $JDV-J203-TypeOrganisationInterne-ROR (required)
^short ajouté sur les slices

2023-03-10 09:50 UTC, paulineheurtebise commented on input/fsh/aliases.fsh
>  Alias: $JDV-J236-TypeIdentifiant-ROR = https://mos.esante.gouv.fr/NOS/JDV_J236-TypeIdentifiant-ROR/FHIR/JDV-J236-TypeIdentifiant-ROR
Fait

2023-03-10 09:50 UTC, paulineheurtebise commented on input/fsh/extensions/RORContactFunctionContact.fsh
> +* ^context.expression = "BackboneElement" //TODO question Tristan --> verif Backbone
Corrigé avec URL de l'extension

2023-03-10 09:51 UTC, paulineheurtebise commented on input/fsh/extensions/RORHealthcareServiceContact.fsh
> +* extension[telecommunication].value[x] only ContactPoint //TODO ContactPoint étendu avec nos extensions (organization)
Fait - corrigé on a mis le détail des extension de telecom

2023-03-10 09:51 UTC, paulineheurtebise commented on input/fsh/extensions/RORHealthcareServiceContact.fsh
> +* extension[name].value[x] only string
Ajouté sur tous les éléments

2023-03-10 09:52 UTC, paulineheurtebise commented on input/fsh/profiles/RORHealthcareService.fsh
> +* meta.tag[codeRegion] from $JDV_J237-RegionOM-ROR (required)
^short ajouté au niveau du slicing

2023-03-10 09:52 UTC, paulineheurtebise commented on input/fsh/profiles/RORLocation.fsh
> +* meta.tag ^slicing.description = "Slicing pour gérer le code région définissant la région source des données"
corrigé

2023-03-10 09:52 UTC, paulineheurtebise commented on input/fsh/profiles/ROROrganization.fsh
>  * identifier[idNatStruct].type from $JDV-J236-TypeIdentifiant-ROR (required)
Corrigé

2023-03-10 09:53 UTC, paulineheurtebise commented on input/fsh/profiles/ROROrganization.fsh
> +* identifier[idNatStruct].type = $JDV-J236-TypeIdentifiant-ROR#40 (exactly)
Corrigé

2023-03-10 09:53 UTC, paulineheurtebise commented on input/fsh/profiles/ROROrganization.fsh
> +* type 1..*
Cardinalités des slices corrigées en fonction du total des minimums

2023-03-10 09:53 UTC, paulineheurtebise commented on input/fsh/profiles/RORPractitioner.fsh
> +* meta.tag ^slicing.description = "Slicing pour gérer le code région définissant la région source des données"
Corrigé

2023-03-10 09:55 UTC, paulineheurtebise commented on input/fsh/extensions/RORHealthcareServiceContact.fsh
> +    name 0..1 and
descirption ajoutée

2023-03-10 09:55 UTC, paulineheurtebise commented on input/fsh/profiles/ROROrganization.fsh
>  * identifier[numSIREN].type ^fixedCodeableConcept.coding.system = "https://mos.esante.gouv.fr/NOS/JDV_J236-TypeIdentifiant-ROR/FHIR/JDV-J236-TypeIdentifiant-ROR/"
Corrigé

2023-03-10 09:56 UTC, paulineheurtebise commented on input/fsh/profiles/RORPractitioner.fsh
> +* meta.tag 0..1
id et méta corrigé

2023-03-10 15:33 UTC, paulineheurtebise commented on input/fsh/extensions/ROROrganizationAddressLineISO21090AdxpLocality.fsh
>  Description: "Extension créée dans le cadre du ROR"
Extension supprimée car non utilisée

2023-03-13 13:51 UTC, nriss commented on input/fsh/extensions/ROROrganizationEGLocation.fsh
> +    postalBox 0..1 and
A renommer postBox plutôt que postalBox pour être iso annuaire
https://simplifier.net/packages/ans.annuaire.fhir.r4/0.2.0/files/421672
Vu avec @sdemeyANS @jcserafini

2023-03-13 14:11 UTC, nriss commented
Dans le QA, il y a des erreurs sur les urls canoniques des SearchParam, où avez-vous trouvé ces URLs ?

![image](https://user-images.githubusercontent.com/48218773/224726842-420ce0db-d66b-4ac9-8f41-f2c2e001f856.png)

2023-04-04 13:26 UTC, nriss commented
Avez-vous bien vérifié qu'il n'existe pas d'extensions internationales à réutiliser ? Que chacune des extensions est vraiment indispensable ?
Je trouve que ce projet utilise beaucoup d'extensions custom, c'est pas très interopérable ...

2023-04-04 14:08 UTC, sdemeyANS requested changes

2023-04-04 14:08 UTC, sdemeyANS commented on input/fsh/profiles/ROROrganization.fsh
> +    ROROrganizationEGLocation named ror-organization-eg-location 0..1 and
voir commentaire sur l'extension

2023-04-04 14:08 UTC, sdemeyANS commented on input/fsh/profiles/ROROrganization.fsh
> +    ROROrganizationEGName named ror-organization-eg-name 0..1 and
voir commentaire sur l'extension

2023-04-04 14:08 UTC, sdemeyANS commented on input/fsh/profiles/ROROrganization.fsh
> +    organization-period named openingClosingDate 0..1 and
pourquoi le nom n'est pas uniforme ?

2023-04-04 14:08 UTC, sdemeyANS commented on input/fsh/profiles/ROROrganization.fsh
> +    ROROrganizationOIName named ror-organization-oi-name 1..1 and
voir commentaire sur l'extension

2023-04-04 14:08 UTC, sdemeyANS commented on input/fsh/profiles/RORPractitioner.fsh
> +    RORPractitionerTitle named ror-practitioner-title 0..1 and
voir commentaire sur l'extension

2023-04-04 15:12 UTC, nriss commented on input/fsh/extensions/RORCalculatedDistance.fsh
> +Description: "Extension créée dans le cadre du ROR"
Description à compléter

2023-04-04 15:17 UTC, nriss commented on input/fsh/profiles/ROROrganization.fsh
> +    ROROrganizationPeriod named ror-organization-period 0..1 and
Naming et casse à améliorer

2023-04-05 08:24 UTC, sly-kereval commented on input/fsh/extensions/RORTerritorialDivision.fsh
> +* extension[codeTerritorialDivision].value[x] only CodeableConcept // Possible de limiter les valeurs à 2 ou plus JDV ?
Fait

2023-04-05 08:25 UTC, sly-kereval commented on input/fsh/extensions/ROROrganizationEGLocation.fsh
> +    postalBox 0..1 and
Fait

2023-04-05 08:46 UTC, sly-kereval commented on input/fsh/extensions/RORMetaCreationDate.fsh
> +Description: "Extension créée dans le cadre du ROR qui correspond à la date de création (dans le ROR régionnal) présente dans les métadonnées."
Corrigé

2023-04-05 09:04 UTC, sly-kereval commented on ig.ini
> +ig = fsh-generated/resources/ImplementationGuide-ans.fhir.fr.ror30.json
Corrigé

2023-04-06 12:23 UTC, TristanKEREVAL commented on input/fsh/extensions/ROROrganizationEGLocation.fsh
Visiblement ce qui a été fait avait comme objectif de faire regrouper les information d'1 élément ou plus (exemple EG,EJ qui sont tout les 2 sur ROROrganization) métier au sein d'un même profil. Donc si on repart sur une implémentation proche de FHIR on va séparer les infos dans différentes ressources, par exemple on pour les attributs propres à la location d'un EG, on va les retrouver dans RORLocation, ou alors vous voulez un profil RORLocationEG spécifique car RORLocation impose des éléments qui n'ont pas vocation à être rempli avec location d'un EG

2023-04-06 12:26 UTC, TristanKEREVAL commented on input/fsh/extensions/ROROrganizationEGName.fsh
Il faut transporter le nom d'un EG L'attribut Name de la ressource est déjà utilisé (mappé raison sociale) et est de cardinalité max 1 donc on ne peut pas slicer . On peut utiliser l'alias présent de base dans la ressource mais on s'éloignerait de la définition FHIR de l'attribut

2023-04-06 12:27 UTC, TristanKEREVAL commented on input/fsh/extensions/ROROrganizationOIName.fsh
Pareil qu'au dessus, à la limite on peut rassembler les 2 noms sous un seul attribut (extension ou non à voir) qu'on remplirait soit par le nom EG soit par le nom OI

2023-04-06 12:31 UTC, TristanKEREVAL commented on input/fsh/extensions/RORPractitionerTitle.fsh
On supprime cette extension qui représentatit la civilité d'une personne physique (Mr,Mme...) et on va mapper cette attribut métier sur name.prefix. Ça vous va ? Comme on applique pas de contrainte

2023-04-06 12:40 UTC, TristanKEREVAL commented on input/fsh/instances/ror-sp-organization-oi-name.fsh
Cas d'usage présent dans la spec (voir 3.3.4 de la spec)

2023-04-06 12:49 UTC, TristanKEREVAL commented on input/fsh/extensions/RORCalculatedDistance.fsh
> +Description: "Extension créée dans le cadre du ROR"
On a pas l'info métier, pas de correspondance dans le modèle d'expo mais d'après Pauline c'était normal. On pourra décrire d'avantage à son retour et pour l'instant on peut juste mettre la traduction : Extension créer pour transporter la distance calculée

2023-04-06 15:08 UTC, TristanKEREVAL commented on input/fsh/extensions/ROROrganizationEGLocation.fsh
Ne garder que le profil RORLocation et supprimer l'extension de ROROrganization

2023-04-06 15:36 UTC, TristanKEREVAL commented on input/fsh/profiles/ROROrganization.fsh
> +* type[OIType] ^short = "typeOI (OI) : Type d'organisation interne"
On utilise des règles de gestions, on conditionne le type par rapport à la présence d'un id OI alors la cardinalité des champs spécifiques OI s'actualise et pareil pour EG et EJ-> Rajouter dans le SHORT du slicing -> Commentaire général pour réexpliquer le process

2023-04-06 15:36 UTC, TristanKEREVAL commented on input/fsh/profiles/ROROrganization.fsh
> +* type[categorieEtablissement] ^short = "categorieEG (EG) : "
Voir précédent

2023-04-06 15:40 UTC, TristanKEREVAL commented on input/fsh/profiles/ROROrganization.fsh
> +    organization-period named openingClosingDate 0..1 and
Sortir les 3 extensions de l'extension complexe pour faire 3 simple

2023-04-07 07:12 UTC, TristanKEREVAL commented on input/fsh/instances/ror-sp-organization-oi-name.fsh
Paramètre à modifier en fonction de la réponse de Jean Claude

2023-04-07 09:36 UTC, sly-kereval commented on input/fsh/extensions/ROROrganizationEGLocation.fsh
Fait

2023-04-11 09:16 UTC, sdemeyANS approved these changes
revue faite suite  à la relivraison et la résolution de conflits par Kereval

2023-04-11 09:17 UTC, nriss approved these changes

2023-04-11 09:21 UTC, sly-kereval commented on input/fsh/extensions/ROROrganizationEGName.fsh
Après discussion, l'extension a été conservée.

2023-04-11 09:22 UTC, sly-kereval commented on input/fsh/extensions/ROROrganizationOIName.fsh
Après discussion, l'attribut nomOI a été déplacé dans un slice de alias.

2023-04-11 09:23 UTC, sly-kereval commented on input/fsh/profiles/ROROrganization.fsh
> +* type[OIType] ^short = "typeOI (OI) : Type d'organisation interne"
Après discussion, finalement l'utilisation de règles de gestion ne semblait pas pertinente pour l'instant, donc pas de modification.

2023-04-11 09:25 UTC, sly-kereval commented on input/fsh/instances/ror-sp-organization-oi-name.fsh
Fait

2023-04-11 09:26 UTC, merged

2023-04-11 10:20 UTC, sly-kereval commented on input/fsh/extensions/ROROrganizationEGName.fsh
Attributs déplacés dans des slices de alias.