Correction issue
ansforge/IG-fhir-repertoire-offre-ressources-sante pull request #70
Opened 2023-06-29 15:12 UTC by sly-kereval

Les attributs liés à télécommunication ont été déplacés dans une extension à part (RORHealthcareServiceContactTelecom), qui est appelée dans l'extension RORHealthcareServiceContact avec pour cardinalité 0..*.

2023-06-29 15:35 UTC, nriss commented
Ne pas utiliser d'accent dans le nom des branches, ça affiche un message d'erreur 
<img width="1086" alt="image" src="https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/assets/48218773/b3b799e4-f5ca-4838-9189-b1470ff0a56e">

2023-06-29 15:51 UTC, nriss requested changes

2023-06-29 15:51 UTC, nriss commented on input/fsh/extensions/RORHealthcareServiceContactTelecom.fsh
> +Id: ror-healthcareservice-contatc-telecom
C'est pas vraiment ContactTelecom mais c'est des metadata à propos du contact, il faudrait changer le nom

2023-06-29 15:51 UTC, nriss commented on input/fsh/extensions/RORHealthcareServiceContact.fsh
>      purposeContact 0..1 and
Pourquoi est-ce que HealthcareService a une extension contact alors qu'il y a un champs telecom ? Assez complexe à comprendre pour l'écosystème la différence

2023-06-29 16:01 UTC, nriss requested changes

2023-06-29 16:01 UTC, nriss commented on input/fsh/extensions/RORTelecomCommunicationChannel.fsh
> +* ^context[=].expression = "https://interop.esante.gouv.fr/ig/fhir/ror/StructureDefinition/ror-healthcareservice-contact-telecom"
Vérifier si les 3 extensions sont définies ailleurs.

Si elles ne sont pas définies ailleurs, il suffit de définir une extension complexe en un seul fichier plutôt que de créer 4 fichiers.

2023-06-29 16:01 UTC, nriss commented on input/fsh/extensions/RORHealthcareServiceContact.fsh
>      purposeContact 0..1 and
Cette extension ne devrait pas être appliquée à HealthcareService.telecom plutôt ?

2023-07-03 08:29 UTC, sly-kereval commented on input/fsh/extensions/RORHealthcareServiceContactTelecom.fsh
> +Id: ror-healthcareservice-contatc-telecom
La typo est corrigé, merci.
Cette extension regroupe de 4 attributs de la classe Telecommunication pour l'attribut contact de la classe OffreOperationnelle.

2023-07-03 08:31 UTC, sly-kereval commented on input/fsh/extensions/RORHealthcareServiceContact.fsh
>      purposeContact 0..1 and
Le champ telecom est déjà utilisé pour boiteLettreMSS.

2023-07-03 08:31 UTC, sly-kereval commented on input/fsh/extensions/RORTelecomCommunicationChannel.fsh
> +* ^context[=].expression = "https://interop.esante.gouv.fr/ig/fhir/ror/StructureDefinition/ror-healthcareservice-contact-telecom"
Ces 3 extensions sont utilisées aussi ailleurs (Location, Organization ...).

2023-07-03 09:20 UTC, nriss requested changes

2023-07-03 09:20 UTC, nriss commented on input/fsh/extensions/RORHealthcareServiceContact.fsh
>      purposeContact 0..1 and
HealthcareService.telecom n'est pas forcément une BAL MSS : il faut créer une slice pour la BAL, et laisser l'opportunité de rajouter d'autres telecom.
Ainsi, on pourra placer cette extension dans telecom

2023-07-03 09:20 UTC, nriss commented on input/fsh/extensions/RORTelecomCommunicationChannel.fsh
> +* ^context[=].expression = "https://interop.esante.gouv.fr/ig/fhir/ror/StructureDefinition/ror-healthcareservice-contact-telecom"
Et dans ces autres profils, est-ce que ces extensions peuvent être mutualisées au sein d'une extension complexe ou non ?

2023-07-03 09:23 UTC, nriss commented on input/fsh/extensions/RORTelecomCommunicationChannel.fsh
> +* ^context[=].expression = "https://interop.esante.gouv.fr/ig/fhir/ror/StructureDefinition/ror-healthcareservice-contact-telecom"
Cf exemple US core ethnicity : https://build.fhir.org/ig/HL7/fhir-shorthand/reference.html#defining-extensions

2023-07-06 11:50 UTC, sly-kereval commented on input/fsh/extensions/RORHealthcareServiceContact.fsh
>      purposeContact 0..1 and
Dans le ME, la classe BoiteLettreMSS contient uniquement un attribut adresseMSS de type Telecommunication alors que la classe Contact contient un attribut telecommunication de type Telecommunication mais aussi d'autres attributs (nom, fonctionContact ...), c'est pour cela qu'une extension a été créée.

2023-07-06 12:04 UTC, sly-kereval commented on input/fsh/extensions/RORTelecomCommunicationChannel.fsh
> +* ^context[=].expression = "https://interop.esante.gouv.fr/ig/fhir/ror/StructureDefinition/ror-healthcareservice-contact-telecom"
Ces 3 extensions sont utilisées ensemble pour étendre : 
- HealthcareService.telecom
- Location.telecom
- Organization.telecom et Organization.contact.telecom
- Practitioner.telecom
- PractitionerRole.telecom 
L'extension RORHealthcareServiceContactTelecom contient en plus l'attribut telecomAddress car pour le moment on étend pas telecom (voir discussion ci-dessus). 
Il est donc possible de regrouper ces extensions dans une extension complexe, à valider au niveau impact sur les développements déjà réalisés.

2023-07-06 14:25 UTC, nriss commented on input/fsh/extensions/RORTelecomCommunicationChannel.fsh
> +* ^context[=].expression = "https://interop.esante.gouv.fr/ig/fhir/ror/StructureDefinition/ror-healthcareservice-contact-telecom"
Ok pour moi pour faire une extension complexe du coup :)

Il y a énormément d'extensions dans ce projet, c'est pas une bonne pratique, si on peut en rassembler ensemble, c'est déjà bcp mieux

2023-07-06 14:27 UTC, nriss commented on input/fsh/extensions/RORHealthcareServiceContact.fsh
>      purposeContact 0..1 and
Le plus important, c'est d'être FHIR compliant et le plus logique possible, il ne faut pas chercher à coller absolument au ME, on peut aussi faire des mappings pour aller dans d'autres attributs plus pertinents

Pour moi, il devrait y avoir:
- une slice telecom mss qui contient les extensions pour la BAL mss
- une slice telecom correspondant à la classe contact

Ca te conviendrait ?

PArce que la BALMSS est clairement un point de contact de l'HS, donc ça aurait tout les sens que le mapping se faisse vers HealthcareService.telecom

2023-07-07 07:32 UTC, hwn-atos commented
Bonjour,

Je voulais vous informer que le changement réalisé dans les fichiers .fsh nous permet bien d'avoir plusieurs télécommunications pour un contact du Healthcareservice.

Cependant notre validateur FHIR nous indique les quatre erreurs suivantes, qui semblent être liées à ce changement:

 - Pour une extension `ror-healthcareservice-contact`:
```
The modifier extension https://interop.esante.gouv.fr/ig/fhir/ror/StructureDefinition/ror-confidentiality-level is not allowed to be used at this point (allowed = e:ContactPoint, e:BackboneElement, e:Location.telecom; this element is [HealthcareService.extension, Extension])

The modifier extension https://interop.esante.gouv.fr/ig/fhir/ror/StructureDefinition/ror-healthcareservice-contact-telecom is not allowed to be used at this point (allowed = e:https://interop.esante.gouv.fr/ig/fhir/ror/StructureDefinition/ror-healthcareservice-contact; this element is [HealthcareService.extension, Extension])
```

- Pour une extension `ror-healthcareservice-contact-telecom`:
```
The modifier extension https://interop.esante.gouv.fr/ig/fhir/ror/StructureDefinition/ror-telecom-communication-channel is not allowed to be used at this point (allowed = e:ContactPoint, x:https://interop.esante.gouv.fr/ig/fhir/ror/StructureDefinition/ror-healthcareservice-contact-telecom; this element is [HealthcareService.extension.extension, Extension.extension, Extension])

The modifier extension https://interop.esante.gouv.fr/ig/fhir/ror/StructureDefinition/ror-telecom-confidentiality-level is not allowed to be used at this point (allowed = e:ContactPoint, x:https://interop.esante.gouv.fr/ig/fhir/ror/StructureDefinition/ror-healthcareservice-contact-telecom; this element is [HealthcareService.extension.extension, Extension.extension, Extension])
```
Après une rapide analyse, on dirait:
- qu'il manque une entrée dans le contexte de l'extension `ror-confidentiality-level`, pour l'extension `ror-healthcareservice-contact`
- que le validateur ne reconnait pas l'extension renseignée dans le contexte des extensions  `ror-contact-function-contact`, `ror-telecom-communication-channel` et `ror-telecom-confidentiality-level`, lorsqu'elle est renseignée de cette manière:
```
* ^context[+].type = #extension
* ^context[=].expression = "url-canonique-extension"
```

Si on essaye de mettre la valeur suggérée par la validateur dans le contexte, c'est à dire:
```
* ^context[+].type = #element
* ^context[=].expression = "HealthcareService.extension"
```
l'erreur disparaît.

Ces erreurs du validateur sont-elles véridiques ?

Hugo,  
Développeur sur le projet du ROR-National.

2023-07-07 13:39 UTC, nriss commented
Merci pour ton retour ! 
Bien vu, il faut effectivement bien adapter les contextes @sly-kereval

2023-07-10 13:41 UTC, hwn-atos commented
> revoir les derniers commentaires d'Hugo svp

Comme demandé, voici la PR pour la proposition de correction: #76

2023-09-15 09:46 UTC, paulineheurtebise commented
PR abandonnée car mise à plat de la problématique et traitement globale des telecom et Contact dans une prochaine PR

2023-09-15 09:46 UTC, closed without merging